package main

/*
#include <stdlib.h>
*/
import "C"

import (
	"strings"
	"unsafe"

	"github.com/OpenNHP/opennhp/endpoints/agent/sdk"
)

func deepCopyCString(c_str *C.char) string {
	if c_str == nil {
		return ""
	}
	return strings.Clone(C.GoString(c_str))
}

// Release the memory of the string buffer generated by NHPSDK.
//
//export nhp_free_cstring
func nhp_free_cstring(ptr *C.char) {
	C.free(unsafe.Pointer(ptr))
}

//export nhp_agent_init
func nhp_agent_init(workingDir *C.char, logLevel C.int) bool {
	return sdk.Init(deepCopyCString(workingDir), int(logLevel))
}

//export nhp_agent_close
func nhp_agent_close() {
	sdk.Close()
}

//export nhp_agent_knockloop_start
func nhp_agent_knockloop_start() C.int {
	return C.int(sdk.KnockloopStart())
}

//export nhp_agent_knockloop_stop
func nhp_agent_knockloop_stop() {
	sdk.KnockloopStop()
}

//export nhp_agent_set_knock_user
func nhp_agent_set_knock_user(userId *C.char, devId *C.char, orgId *C.char, userData *C.char) bool {
	return sdk.SetKnockUser(deepCopyCString(userId), deepCopyCString(devId), deepCopyCString(orgId), deepCopyCString(userData))
}

//export nhp_agent_add_server
func nhp_agent_add_server(pubkey *C.char, ip *C.char, host *C.char, port C.int, expire int64) bool {
	return sdk.AddServer(deepCopyCString(pubkey), deepCopyCString(ip), deepCopyCString(host), int(port), expire)
}

//export nhp_agent_remove_server
func nhp_agent_remove_server(pubkey *C.char) {
	sdk.RemoveServer(deepCopyCString(pubkey))
}

//export nhp_agent_add_resource
func nhp_agent_add_resource(aspId *C.char, resId *C.char, serverIp *C.char, serverHostname *C.char, serverPort C.int) bool {
	return sdk.AddResource(deepCopyCString(aspId), deepCopyCString(resId), deepCopyCString(serverIp), deepCopyCString(serverHostname), int(serverPort))
}

//export nhp_agent_remove_resource
func nhp_agent_remove_resource(aspId *C.char, resId *C.char) {
	sdk.RemoveResource(deepCopyCString(aspId), deepCopyCString(resId))
}

//export nhp_agent_knock_resource
func nhp_agent_knock_resource(aspId *C.char, resId *C.char, serverIp *C.char, serverHostname *C.char, serverPort C.int) *C.char {
	return C.CString(sdk.KnockResource(deepCopyCString(aspId), deepCopyCString(resId), deepCopyCString(serverIp), deepCopyCString(serverHostname), int(serverPort)))
}

//export nhp_agent_knock_resource_with_run_id
func nhp_agent_knock_resource_with_run_id(aspId *C.char, resId *C.char, runID *C.char, serverIp *C.char, serverHostname *C.char, serverPort C.int) *C.char {
	return C.CString(sdk.KnockResourceWithRunID(deepCopyCString(aspId), deepCopyCString(resId), deepCopyCString(runID), deepCopyCString(serverIp), deepCopyCString(serverHostname), int(serverPort)))
}

//export nhp_agent_knock_resource_with_run_binding
func nhp_agent_knock_resource_with_run_binding(aspId *C.char, resId *C.char, runID *C.char, runAttempt C.ulonglong, serverIp *C.char, serverHostname *C.char, serverPort C.int) *C.char {
	return C.CString(sdk.KnockResourceWithRunBinding(deepCopyCString(aspId), deepCopyCString(resId), deepCopyCString(runID), uint64(runAttempt), deepCopyCString(serverIp), deepCopyCString(serverHostname), int(serverPort)))
}

//export nhp_agent_exit_resource
func nhp_agent_exit_resource(aspId *C.char, resId *C.char, serverIp *C.char, serverHostname *C.char, serverPort C.int) bool {
	return sdk.ExitResource(deepCopyCString(aspId), deepCopyCString(resId), deepCopyCString(serverIp), deepCopyCString(serverHostname), int(serverPort))
}

//export nhp_agent_exit_resource_with_run_id
func nhp_agent_exit_resource_with_run_id(aspId *C.char, resId *C.char, runID *C.char, serverIp *C.char, serverHostname *C.char, serverPort C.int) bool {
	return sdk.ExitResourceWithRunID(deepCopyCString(aspId), deepCopyCString(resId), deepCopyCString(runID), deepCopyCString(serverIp), deepCopyCString(serverHostname), int(serverPort))
}

//export nhp_agent_retire_session
func nhp_agent_retire_session(knockAckJSON *C.char, serverIp *C.char, serverHostname *C.char, serverPort C.int) *C.char {
	return C.CString(retireSessionJSON(deepCopyCString(knockAckJSON), deepCopyCString(serverIp), deepCopyCString(serverHostname), int(serverPort)))
}

func retireSessionJSON(knockAckJSON, serverIP, serverHostname string, serverPort int) string {
	return sdk.RetireSession(knockAckJSON, serverIP, serverHostname, serverPort)
}

//export nhp_generate_keys
func nhp_generate_keys() *C.char {
	return C.CString(sdk.GenerateKeys())
}

//export nhp_privkey_to_pubkey
func nhp_privkey_to_pubkey(privateBase64 *C.char) *C.char {
	result := sdk.PrivkeyToPubkey(deepCopyCString(privateBase64))
	if result == "" {
		return nil
	}
	return C.CString(result)
}
