//go:build linux

package ac

import (
	"testing"
	"time"
)

// TestParseIpsetSaveLine fences the `ipset save` line parser
// against every shape HandleAccessControl writes to defaultset
// (plus the negative shapes the parser must reject).
func TestParseIpsetSaveLine(t *testing.T) {
	cases := []struct {
		name   string
		line   string
		want   ipsetEntry
		wantOk bool
	}{
		{
			name:   "bare-port-tcp",
			line:   "add defaultset 192.0.2.1,443,192.0.2.2 timeout 285",
			want:   ipsetEntry{srcIP: "192.0.2.1", dstIP: "192.0.2.2", port: 443, proto: FlowProtoTCP, remaining: 285 * time.Second},
			wantOk: true,
		},
		{
			name:   "tcp-prefix",
			line:   "add defaultset 192.0.2.1,tcp:443,192.0.2.2 timeout 100",
			want:   ipsetEntry{srcIP: "192.0.2.1", dstIP: "192.0.2.2", port: 443, proto: FlowProtoTCP, remaining: 100 * time.Second},
			wantOk: true,
		},
		{
			name:   "udp-prefix",
			line:   "add defaultset 10.0.0.5,udp:53,10.0.0.6 timeout 50",
			want:   ipsetEntry{srcIP: "10.0.0.5", dstIP: "10.0.0.6", port: 53, proto: FlowProtoUDP, remaining: 50 * time.Second},
			wantOk: true,
		},
		{
			name:   "icmp-echo",
			line:   "add defaultset 192.0.2.1,icmp:8/0,192.0.2.2 timeout 30",
			want:   ipsetEntry{srcIP: "192.0.2.1", dstIP: "192.0.2.2", port: 0, proto: FlowProtoICMP, remaining: 30 * time.Second},
			wantOk: true,
		},
		// Negatives — must reject
		{
			name:   "create-line",
			line:   "create defaultset hash:ip,port,ip family inet hashsize 1024 maxelem 65536 timeout 305",
			wantOk: false,
		},
		{
			name:   "comment",
			line:   "# Generated by ipset",
			wantOk: false,
		},
		{
			name:   "port-range-rejected",
			line:   "add tempset 192.0.2.1,1-65535,192.0.2.2 timeout 10",
			wantOk: false,
		},
		{
			name:   "missing-timeout",
			line:   "add defaultset 192.0.2.1,443,192.0.2.2",
			wantOk: false,
		},
		{
			name:   "zero-timeout-rejected",
			line:   "add defaultset 192.0.2.1,443,192.0.2.2 timeout 0",
			wantOk: false,
		},
		{
			name:   "unknown-proto-rejected",
			line:   "add defaultset 192.0.2.1,sctp:443,192.0.2.2 timeout 60",
			wantOk: false,
		},
		{
			name:   "malformed-tuple",
			line:   "add defaultset 192.0.2.1 timeout 100",
			wantOk: false,
		},
		{
			name:   "empty",
			line:   "",
			wantOk: false,
		},
		// ipset 7.x with the `comment` flag enabled: comment after
		// timeout. Parser walks for the "timeout" token so this
		// still resolves to fields[3]=timeout, fields[4]=285 (cr
		// fence: round 13 nit 3).
		{
			name:   "comment-flag-trailing",
			line:   `add defaultset 192.0.2.1,tcp:443,192.0.2.2 timeout 285 comment "operator note"`,
			want:   ipsetEntry{srcIP: "192.0.2.1", dstIP: "192.0.2.2", port: 443, proto: FlowProtoTCP, remaining: 285 * time.Second},
			wantOk: true,
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, ok := parseIpsetSaveLine(c.line)
			if ok != c.wantOk {
				t.Fatalf("ok: got %v want %v (got entry: %+v)", ok, c.wantOk, got)
			}
			if !ok {
				return
			}
			if got.srcIP != c.want.srcIP {
				t.Errorf("srcIP: got %q want %q", got.srcIP, c.want.srcIP)
			}
			if got.dstIP != c.want.dstIP {
				t.Errorf("dstIP: got %q want %q", got.dstIP, c.want.dstIP)
			}
			if got.port != c.want.port {
				t.Errorf("port: got %d want %d", got.port, c.want.port)
			}
			if got.proto != c.want.proto {
				t.Errorf("proto: got %s want %s", got.proto, c.want.proto)
			}
			if got.remaining != c.want.remaining {
				t.Errorf("remaining: got %s want %s", got.remaining, c.want.remaining)
			}
		})
	}
}

// TestFlowKeyFromIpsetEntry fences the FlowKey construction path,
// including the IP-validity check the parser layer delegates to
// MakeFlowKey.
func TestFlowKeyFromIpsetEntry(t *testing.T) {
	t.Run("happy-path", func(t *testing.T) {
		e := ipsetEntry{srcIP: "192.0.2.1", dstIP: "192.0.2.2", port: 443, proto: FlowProtoTCP}
		k, err := flowKeyFromIpsetEntry(e)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if k.DstPort != 443 || k.Protocol != FlowProtoTCP {
			t.Errorf("unexpected FlowKey: %+v", k)
		}
	})
	t.Run("malformed-src", func(t *testing.T) {
		e := ipsetEntry{srcIP: "not-an-ip", dstIP: "192.0.2.2", port: 443, proto: FlowProtoTCP}
		if _, err := flowKeyFromIpsetEntry(e); err == nil {
			t.Error("expected error on malformed src IP")
		}
	})
	t.Run("malformed-dst", func(t *testing.T) {
		e := ipsetEntry{srcIP: "192.0.2.1", dstIP: "not-an-ip", port: 443, proto: FlowProtoTCP}
		if _, err := flowKeyFromIpsetEntry(e); err == nil {
			t.Error("expected error on malformed dst IP")
		}
	})
	t.Run("unspecified-rejected", func(t *testing.T) {
		// 0.0.0.0 reaches MakeFlowKey which rejects via its own
		// boundary check — confirm the rejection propagates.
		e := ipsetEntry{srcIP: "0.0.0.0", dstIP: "192.0.2.2", port: 443, proto: FlowProtoTCP}
		if _, err := flowKeyFromIpsetEntry(e); err == nil {
			t.Error("expected error on 0.0.0.0 src IP")
		}
	})
}

// FuzzParseIpsetSaveLine ensures the parser never panics on
// adversarial / malformed input. The parser's only failure mode
// should be (ipsetEntry{}, false) — never a panic, OOB index, or
// runaway allocation. A future kernel ipset locale variant or
// truncated stdout could produce shapes the table tests don't
// enumerate; this fuzz target catches those before they reach the
// scheduler
func FuzzParseIpsetSaveLine(f *testing.F) {
	// Seed with happy + negative cases so the fuzzer starts from
	// known-shape coverage and mutates outward.
	for _, seed := range []string{
		"add defaultset 192.0.2.1,443,192.0.2.2 timeout 285",
		"add defaultset 192.0.2.1,tcp:443,192.0.2.2 timeout 100",
		"add defaultset 10.0.0.5,udp:53,10.0.0.6 timeout 50",
		"add defaultset 192.0.2.1,icmp:8/0,192.0.2.2 timeout 30",
		"create defaultset hash:ip,port,ip family inet hashsize 1024 maxelem 65536 timeout 305",
		"# Generated by ipset",
		"add tempset 192.0.2.1,1-65535,192.0.2.2 timeout 10",
		"add defaultset 192.0.2.1,443,192.0.2.2",
		"add defaultset 192.0.2.1,443,192.0.2.2 timeout 0",
		"add defaultset 192.0.2.1,sctp:443,192.0.2.2 timeout 60",
		"add defaultset 192.0.2.1 timeout 100",
		"",
		// ipset 7.x with the `comment` flag enabled — comment after
		// timeout. The walk-for-token parser must skip the trailing
		// comment fields cleanly
		`add defaultset 192.0.2.1,tcp:443,192.0.2.2 timeout 285 comment "hello world"`,
		// Pathological: literal "timeout" inside the comment.
		// Walk-for-token short-circuits on the first `timeout` it
		// sees, so this still parses correctly for the real timeout
		// at fields[3].
		`add defaultset 192.0.2.1,tcp:443,192.0.2.2 timeout 285 comment "timeout in comment"`,
		// Whitespace in comment.
		`add defaultset 192.0.2.1,tcp:443,192.0.2.2 timeout 285 comment "with spaces and \"quotes\""`,
	} {
		f.Add(seed)
	}
	f.Fuzz(func(t *testing.T, line string) {
		// Goal: no panic, no OOB, no infinite loop. Whatever the
		// parser returns is fine.
		entry, ok := parseIpsetSaveLine(line)
		// If parsing succeeded, flowKeyFromIpsetEntry shouldn't
		// panic either — it's the next hop in the pipeline.
		if ok {
			_, _ = flowKeyFromIpsetEntry(entry)
		}
	})
}

// TestIsIpsetSetNotFoundStderr fences the C-locale stderr text
// classification ipset uses for "set doesn't exist." Wordings come
// from observed `ipset 6.x` / `7.x` output. The matcher is
// name-anchored on the 6.x branch so an element-level "does not
// exist" in the stderr cannot reclassify to whole-set-absent; the
// generic 7.x phrasing matches structurally without a name anchor.
func TestIsIpsetSetNotFoundStderr(t *testing.T) {
	matchCases := []struct {
		stderr  string
		setName string
	}{
		// ipset 7.x typical output — no name in text, classified
		// structurally.
		{"ipset v7.15: The set with the given name does not exist", "defaultset"},
		// ipset 6.x alternate — name-anchored.
		{"ipset v6.38: Set defaultsetv6 does not exist", "defaultsetv6"},
		// userspace cache miss.
		{"ipset v7.15: Element cannot be added to the set: set not in cache", "defaultset"},
	}
	for _, c := range matchCases {
		if !isIpsetSetNotFoundStderr(c.stderr, c.setName) {
			t.Errorf("expected MATCH on %q (set=%s); should classify as set-not-found", c.stderr, c.setName)
		}
	}
	nonMatchCases := []struct {
		stderr  string
		setName string
	}{
		{"ipset v7.15: Operation not permitted", "defaultset"},
		{"ipset v7.15: Kernel error received: Address family not supported by protocol", "defaultset"},
		{"", "defaultset"},
		{"Connection timed out", "defaultset"},
		// Name-anchored 6.x phrasing must NOT classify when the set
		// name doesn't appear — this guards against ambiguous
		// element-level "does not exist" stderr being silently
		// swallowed as whole-set-absent.
		{"Set otherset does not exist", "defaultset"},
		// Element-level error containing "does not exist" without the
		// 7.x generic phrasing or the set name.
		{"ipset v7.15: Element foo does not exist in set bar", "defaultset"},
	}
	for _, c := range nonMatchCases {
		if isIpsetSetNotFoundStderr(c.stderr, c.setName) {
			t.Errorf("expected NO MATCH on %q (set=%s); would silently swallow a real error as set-not-found", c.stderr, c.setName)
		}
	}
}
