#!/usr/bin/env bash
# check-prod-rollout-tasks-body.sh — decide the prod-rollout-tasks PR-body gate.
#
# Pure (no network): reads PR_BODY / PR_DRAFT / PR_AUTHOR from the environment
# and prints exactly one decision token to stdout (nothing else), or exits
# non-zero with a `::error::` annotation on stderr. Factoring this out of
# .github/workflows/prod-rollout-tasks.yml lets the Dependabot/draft exemptions
# and the exactly-one-box parsing be unit-tested by
# tests/scripts/check-prod-rollout-tasks-body_test.sh (fenced in
# validate-workflows.yml) — actionlint can shellcheck the embedded script but
# cannot exercise its branches.
#
# The one network-dependent rule — that an "Added a ledger entry" choice
# actually changed a ledger file — stays in the workflow, which calls this
# script first and only fetches the PR diff when the token is `select:added`.
#
# Decision tokens (stdout, exit 0):
#   pass:dependabot  — author is dependabot[bot]; exempt (see workflow comment)
#   pass:draft       — draft PR; re-checked when marked ready for review
#   select:none      — exactly one box: "Confirmed this PR has no prod rollout tasks"
#   select:added     — exactly one box: "Added a prod rollout ledger entry"
#                      (the caller must confirm a ledger file is in the diff)
#
# Errors (stderr `::error::`, exit 1):
#   missing `## Prod Rollout Tasks` section, or not exactly one box checked.
#
# A named token (rather than a bare exit code) keeps a clean split under the
# caller's `set -e` — any non-zero exit is a real failure to propagate — and
# lets the fixture assert *which* branch fired (e.g. dependabot vs draft),
# which is the point of extracting this logic to be tested.
#
# Keep the checkbox labels in lockstep with .github/PULL_REQUEST_TEMPLATE.md and
# docs/runbooks/prod-rollout-ledger/README.md. The [[:space:]]*$ anchors
# intentionally absorb GitHub's CRLF body lines. Labels must stay regex-safe;
# metacharacters silently change matching semantics.
#
# Usage: PR_BODY=… PR_DRAFT=… PR_AUTHOR=… check-prod-rollout-tasks-body.sh
set -euo pipefail

pr_body="${PR_BODY:-}"
pr_draft="${PR_DRAFT:-}"
pr_author="${PR_AUTHOR:-}"

# Dependabot PRs are exempt: dependency/action bumps are evaluated by the human
# reviewer who must approve them, and Dependabot writes an autogenerated
# changelog body rather than the PR template, so it cannot fill the checkbox.
# Keyed on the PR author, not github.actor, so a maintainer editing the body
# (an `edited` trigger) does not flip the actor and defeat the exemption.
if [ "$pr_author" = "dependabot[bot]" ]; then
	echo "pass:dependabot"
	exit 0
fi

# Draft PRs pass early so required-check branch protection does not block
# work-in-progress; the check re-runs when the PR is marked ready for review.
if [ "$pr_draft" = "true" ]; then
	echo "pass:draft"
	exit 0
fi

if ! printf '%s\n' "$pr_body" | grep -Eq '^##[[:space:]]+Prod Rollout Tasks[[:space:]]*$'; then
	echo "::error::Missing exact '## Prod Rollout Tasks' section in the PR body. Check spelling and capitalization. See docs/runbooks/prod-rollout-ledger/README.md." >&2
	exit 1
fi

# The section runs until the next `## ` (h2) heading. A `### ` sub-heading is
# intentionally NOT a boundary — it is content within the section — so the bound
# matches two hashes followed by whitespace, which `### ` (three hashes) fails.
tasks_section=$(printf '%s\n' "$pr_body" | awk '
	/^##[[:space:]]+Prod Rollout Tasks[[:space:]]*$/ { in_section=1; next }
	/^##[[:space:]]+/ && in_section { exit }
	in_section { print }
')

count_checked() {
	local label="$1"
	# `|| true` keeps a no-match grep from tripping `set -o pipefail`; `grep -c`
	# still prints 0 on no match, so the count is always well-formed.
	printf '%s\n' "$tasks_section" | grep -Ec "^[[:space:]]*[-*+][[:space:]]+\[[xX]\][[:space:]]+${label}[[:space:]]*$" || true
}

added_count=$(count_checked 'Added a prod rollout ledger entry')
notasks_count=$(count_checked 'Confirmed this PR has no prod rollout tasks')
total=$((added_count + notasks_count))

if [ "$total" -ne 1 ]; then
	echo "::error::Choose exactly one Prod Rollout Tasks checkbox in the PR body." >&2
	echo "Found added=$added_count no-tasks=$notasks_count." >&2
	echo "Expected exactly one of these checked lines, with the exact label text; put context elsewhere in the PR body or the ledger entry:" >&2
	echo "- [x] Added a prod rollout ledger entry" >&2
	echo "- [x] Confirmed this PR has no prod rollout tasks" >&2
	exit 1
fi

if [ "$added_count" -eq 1 ]; then
	echo "select:added"
else
	echo "select:none"
fi
