package core

import (
	"bytes"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/OpenNHP/opennhp/nhp/common"
)

// Cross-language fences for the browser js-agent knock loop (#2208 PR-5b). The
// loop (endpoints/js-agent/src/agent/loop.ts) dispatches the server's reply, so
// these fixtures pin every dispatch arm beyond the "0"-success ACK (already
// fenced by ack.json in PR-4):
//   - ack-52024.json:         deny ACK (ErrQurlSessionExpired)  -> reResolve.
//   - ack-error.json:         a generic error ACK               -> serverError.
//   - ack-success-empty.json: an empty-errCode success ACK      -> success.
//   - cok.json:               an overload cookie reply (NHP_COK) -> cookieChallenge.
//   - ack-uncompressed.json:  an ACK with COMPRESS clear         -> no inflate.
//   - ack-empty-body.json:    a header-only ACK                  -> empty body.
// Plus a body-contract fence: the TS-built AgentKnockMsg must unmarshal into Go's
// struct with the #1154 headerType, qURL plugin routing, and encrypted bootstrap
// token carrier. Generated by Go, decrypted/asserted by BOTH sides.

const (
	ack52024FixturePath        = "../../endpoints/js-agent/test/testdata/ack-52024.json"
	ackErrorFixturePath        = "../../endpoints/js-agent/test/testdata/ack-error.json"
	ackEmptySuccessFixturePath = "../../endpoints/js-agent/test/testdata/ack-success-empty.json"
	ackWrongTypeFixturePath    = "../../endpoints/js-agent/test/testdata/ack-wrongtype.json"
	ackBadJSONFixturePath      = "../../endpoints/js-agent/test/testdata/ack-badjson.json"
	ackUncompressedFixturePath = "../../endpoints/js-agent/test/testdata/ack-uncompressed.json"
	ackEmptyBodyFixturePath    = "../../endpoints/js-agent/test/testdata/ack-empty-body.json"
	cokFixturePath             = "../../endpoints/js-agent/test/testdata/cok.json"
	knockBodyFixturePath       = "../../endpoints/js-agent/test/testdata/knock-body.json"
)

// replyFixture is the shape both sides read for a server reply fixture.
type replyFixture struct {
	ServerStaticPubHex string `json:"serverStaticPubHex"`
	AgentStaticPrivHex string `json:"agentStaticPrivHex"`
	TimestampNanos     string `json:"timestampNanos"`
	BodyHex            string `json:"bodyHex"`
	ReplyPacketHex     string `json:"replyPacketHex"`
}

// sample52024AckMsg is a deny ACK: authenticated, but no active session, so no
// tokens — exactly what the qURL plugin returns on ErrQurlSessionExpired.
func sample52024AckMsg() *common.ServerKnockAckMsg {
	return &common.ServerKnockAckMsg{
		ErrCode: common.ErrQurlSessionExpired.ErrorCode(),
		ErrMsg:  common.ErrQurlSessionExpired.Error(),
	}
}

// sampleErrorAckMsg is a generic error ACK (neither success nor the 52024 deny)
// -> the loop's serverError arm.
func sampleErrorAckMsg() *common.ServerKnockAckMsg {
	return &common.ServerKnockAckMsg{
		ErrCode: common.ErrResourceNotFound.ErrorCode(),
		ErrMsg:  common.ErrResourceNotFound.Error(),
	}
}

// sampleEmptySuccessAckMsg is a success ACK that signals success with an EMPTY
// errCode rather than "0" — a valid protocol state (common.IsSuccessErrCode),
// since ServerKnockAckMsg.ErrCode has no omitempty. The loop must treat it as
// success, not drop the grant's tokens.
func sampleEmptySuccessAckMsg() *common.ServerKnockAckMsg {
	m := sampleAckMsg()
	m.ErrCode = ""
	return m
}

// sampleCookieMsg mirrors what responder.go sendCookie emits in the encrypted
// body: the request transaction id (so the agent can correlate it on re-knock,
// PR-5c) plus a base64 cookie. The fixture below deliberately seals the COK with
// a legacy distinct packet counter because the current JS loop surfaces
// cookieChallenge before the NHP_RKN cookie-answer path; real server COK packets
// now echo the KNK counter on the wire for relay dispatch (#2648).
func sampleCookieMsg() *common.ServerCookieMsg {
	cookie := make([]byte, CookieSize)
	for i := range cookie {
		cookie[i] = byte(i + 1)
	}
	return &common.ServerCookieMsg{
		TransactionId: jsAgentKnockCounter,
		Cookie:        base64.StdEncoding.EncodeToString(cookie),
	}
}

// jsAgentKnockCounter is the knock counter ack-52024.json echoes (the TS loop
// test injects it so the ACK correlation passes). The COK fixture keeps a
// distinct legacy counter to prove today's loop does not require ACK-style COK
// correlation before the cookie-answer path exists.
const (
	jsAgentKnockCounter     uint64 = 0x1122334455667788
	jsAgentLegacyCokCounter uint64 = 0x9988776655443322
)

// sealReply builds a server->agent reply packet (NHP_ACK or NHP_COK) sealed to
// the agent, mirroring the PR-4 ACK generator.
func sealReply(t *testing.T, serverDev *Device, agentPub []byte, headerType int, counter uint64, msg any) replyFixture {
	t.Helper()
	return sealReplyWithCompress(t, serverDev, agentPub, headerType, counter, true, msg)
}

func sealReplyWithCompress(t *testing.T, serverDev *Device, agentPub []byte, headerType int, counter uint64, compress bool, msg any) replyFixture {
	t.Helper()
	body, err := json.Marshal(msg)
	if err != nil {
		t.Fatalf("marshal reply body: %v", err)
	}
	return sealRawReplyWithCompress(t, serverDev, agentPub, headerType, counter, compress, body)
}

// sealRawReply is sealReply with an arbitrary (already-serialized, possibly
// non-JSON) body — used to fence the loop's malformed-body throw path.
func sealRawReply(t *testing.T, serverDev *Device, agentPub []byte, headerType int, counter uint64, body []byte) replyFixture {
	t.Helper()
	return sealRawReplyWithCompress(t, serverDev, agentPub, headerType, counter, true, body)
}

func sealRawReplyWithCompress(t *testing.T, serverDev *Device, agentPub []byte, headerType int, counter uint64, compress bool, body []byte) replyFixture {
	t.Helper()
	mad, err := serverDev.MsgToPacket(&MsgData{
		ConnData:      validatePeerConnectionData(serverDev, 62206, 40000),
		PeerPk:        agentPub,
		HeaderType:    headerType,
		TransactionId: counter,
		Compress:      compress,
		Message:       body,
	})
	if err != nil {
		t.Fatalf("MsgToPacket(%d): %v", headerType, err)
	}
	packet := bytes.Clone(mad.BasePacket.Content)
	tsNanos := mad.LocalInitTime
	mad.Destroy()
	serverPub, _ := base64.StdEncoding.DecodeString(serverDev.PublicKeyBase64())
	agentPriv := validatePeerPrivateKey(0x41)
	return replyFixture{
		ServerStaticPubHex: hex.EncodeToString(serverPub),
		AgentStaticPrivHex: hex.EncodeToString(agentPriv),
		TimestampNanos:     strconv.FormatInt(tsNanos, 10),
		BodyHex:            hex.EncodeToString(body),
		ReplyPacketHex:     hex.EncodeToString(packet),
	}
}

func writeFixture(t *testing.T, path string, fx replyFixture) {
	t.Helper()
	out, err := json.MarshalIndent(fx, "", "  ")
	if err != nil {
		t.Fatalf("marshal fixture: %v", err)
	}
	if err := os.WriteFile(path, append(out, '\n'), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
	t.Logf("wrote %s", path)
}

// fixtureSelected reports whether UPDATE_JS_AGENT_FIXTURES selects the named
// fixture. "1" or "all" regenerates every fixture; a comma-separated list
// regenerates only matching fixture names.
func fixtureSelected(filter, name string) bool {
	if filter == "1" || filter == "all" {
		return true
	}
	for _, part := range strings.Split(filter, ",") {
		if strings.TrimSpace(part) == name {
			return true
		}
	}
	return false
}

// TestJsAgentLoopGenerateFixtures (re)builds the 52024-deny and cookie fixtures.
// Skipped unless UPDATE_JS_AGENT_FIXTURES is set (the server ephemeral is
// random). Set UPDATE_JS_AGENT_FIXTURES=1 or all to regenerate every packet, or
// to a comma-separated list of fixture names (for example
// "ack-uncompressed,ack-empty-body") to regenerate only selected edge fixtures
// without re-randomizing every existing packet.
func TestJsAgentLoopGenerateFixtures(t *testing.T) {
	filter := strings.TrimSpace(os.Getenv("UPDATE_JS_AGENT_FIXTURES"))
	if filter == "" {
		t.Skip("set UPDATE_JS_AGENT_FIXTURES=1/all or a fixture-name list to regenerate the loop fixtures")
	}
	serverDev := NewDevice(NHP_SERVER, validatePeerPrivateKey(0x01), nil)
	agentDev := NewDevice(NHP_AGENT, validatePeerPrivateKey(0x41), nil)
	agentPub, _ := base64.StdEncoding.DecodeString(agentDev.PublicKeyBase64())

	fixtures := []struct {
		name string
		path string
		seal func() replyFixture
	}{
		{
			name: "ack-52024",
			path: ack52024FixturePath,
			seal: func() replyFixture {
				return sealReply(t, serverDev, agentPub, NHP_ACK, jsAgentKnockCounter, sample52024AckMsg())
			},
		},
		{
			name: "ack-error",
			path: ackErrorFixturePath,
			seal: func() replyFixture {
				return sealReply(t, serverDev, agentPub, NHP_ACK, jsAgentKnockCounter, sampleErrorAckMsg())
			},
		},
		{
			name: "ack-success-empty",
			path: ackEmptySuccessFixturePath,
			seal: func() replyFixture {
				return sealReply(t, serverDev, agentPub, NHP_ACK, jsAgentKnockCounter, sampleEmptySuccessAckMsg())
			},
		},
		{
			name: "ack-uncompressed",
			path: ackUncompressedFixturePath,
			seal: func() replyFixture {
				return sealReplyWithCompress(t, serverDev, agentPub, NHP_ACK, jsAgentKnockCounter, false, sampleAckMsg())
			},
		},
		{
			name: "ack-empty-body",
			path: ackEmptyBodyFixturePath,
			seal: func() replyFixture {
				return sealRawReplyWithCompress(t, serverDev, agentPub, NHP_ACK, jsAgentKnockCounter, false, nil)
			},
		},
		{
			name: "cok",
			path: cokFixturePath,
			seal: func() replyFixture {
				return sealReply(t, serverDev, agentPub, NHP_COK, jsAgentLegacyCokCounter, sampleCookieMsg())
			},
		},
		// Throw-path fixtures (the loop rejects these, so only TS asserts the
		// throw): an unexpected (authenticated) reply type, and a malformed
		// (non-JSON) body.
		{
			name: "ack-wrongtype",
			path: ackWrongTypeFixturePath,
			seal: func() replyFixture {
				return sealReply(t, serverDev, agentPub, NHP_LRT, jsAgentKnockCounter, sampleAckMsg())
			},
		},
		{
			name: "ack-badjson",
			path: ackBadJSONFixturePath,
			seal: func() replyFixture {
				return sealRawReply(t, serverDev, agentPub, NHP_ACK, jsAgentKnockCounter, []byte("not json{"))
			},
		},
	}
	known := make([]string, len(fixtures))
	for i, fx := range fixtures {
		known[i] = fx.name
	}
	if filter != "1" && filter != "all" {
		for _, part := range strings.Split(filter, ",") {
			name := strings.TrimSpace(part)
			if name != "" && !slices.Contains(known, name) {
				t.Fatalf("UPDATE_JS_AGENT_FIXTURES selects unknown fixture %q (known: %s)", name, strings.Join(known, ","))
			}
		}
	}
	for _, fx := range fixtures {
		if fixtureSelected(filter, fx.name) {
			writeFixture(t, fx.path, fx.seal())
		}
	}
}

// decryptJsReply drives the real responder path (the agent's view) and returns
// the recovered body — the Go half of the cross-language fence.
func decryptJsReply(t *testing.T, fx replyFixture, headerType int) []byte {
	t.Helper()
	agentPriv, _ := hex.DecodeString(fx.AgentStaticPrivHex)
	serverPub, _ := hex.DecodeString(fx.ServerStaticPubHex)
	packet, _ := hex.DecodeString(fx.ReplyPacketHex)
	wantTs, _ := strconv.ParseInt(fx.TimestampNanos, 10, 64)

	agentDev := NewDevice(NHP_AGENT, agentPriv, nil)
	agentDev.AddPeer(&UdpPeer{
		PubKeyBase64: base64.StdEncoding.EncodeToString(serverPub),
		Ip:           "127.0.0.1",
		Port:         62206,
		Type:         NHP_SERVER,
	})
	var buf PacketBuffer
	copy(buf[:], packet)
	pkt := &Packet{Buf: &buf, Content: buf[:len(packet)], HeaderType: headerType}
	ppd, err := agentDev.createPacketParserData(&PacketData{
		BasePacket: pkt,
		ConnData:   validatePeerConnectionData(agentDev, 40000, 62206),
		InitTime:   wantTs,
	})
	if err != nil {
		t.Fatalf("createPacketParserData: %v", err)
	}
	if err := ppd.validatePeer(); err != nil {
		t.Fatalf("validatePeer: %v", err)
	}
	if err := ppd.decryptBody(); err != nil {
		t.Fatalf("decryptBody: %v", err)
	}
	return ppd.BodyMessage
}

func readReplyFixture(t *testing.T, path string) (replyFixture, bool) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skipf("fixture %s not present (run from the full repo tree)", path)
			return replyFixture{}, false
		}
		t.Fatalf("read %s: %v", path, err)
	}
	var fx replyFixture
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("unmarshal %s: %v", path, err)
	}
	return fx, true
}

// TestJsAgentLoopFixturesRoundTrip is the Go half: it decrypts the deny ACK and
// the cookie reply and asserts the fields the TS loop dispatches on.
func TestJsAgentLoopFixturesRoundTrip(t *testing.T) {
	t.Run("ack-52024", func(t *testing.T) {
		fx, ok := readReplyFixture(t, ack52024FixturePath)
		if !ok {
			return
		}
		var ack common.ServerKnockAckMsg
		if err := json.Unmarshal(decryptJsReply(t, fx, NHP_ACK), &ack); err != nil {
			t.Fatalf("unmarshal ack: %v", err)
		}
		if ack.ErrCode != common.ErrQurlSessionExpired.ErrorCode() {
			t.Errorf("ErrCode = %q, want %q", ack.ErrCode, common.ErrQurlSessionExpired.ErrorCode())
		}
	})
	t.Run("ack-error", func(t *testing.T) {
		fx, ok := readReplyFixture(t, ackErrorFixturePath)
		if !ok {
			return
		}
		var ack common.ServerKnockAckMsg
		if err := json.Unmarshal(decryptJsReply(t, fx, NHP_ACK), &ack); err != nil {
			t.Fatalf("unmarshal ack: %v", err)
		}
		if ack.ErrCode != common.ErrResourceNotFound.ErrorCode() {
			t.Errorf("ErrCode = %q, want %q", ack.ErrCode, common.ErrResourceNotFound.ErrorCode())
		}
	})
	t.Run("ack-success-empty", func(t *testing.T) {
		fx, ok := readReplyFixture(t, ackEmptySuccessFixturePath)
		if !ok {
			return
		}
		var ack common.ServerKnockAckMsg
		if err := json.Unmarshal(decryptJsReply(t, fx, NHP_ACK), &ack); err != nil {
			t.Fatalf("unmarshal ack: %v", err)
		}
		if ack.ErrCode != "" {
			t.Errorf("ErrCode = %q, want empty (implicit success)", ack.ErrCode)
		}
		if !common.IsSuccessErrCode(ack.ErrCode) {
			t.Errorf("IsSuccessErrCode(%q) = false, want true", ack.ErrCode)
		}
	})
	t.Run("ack-uncompressed", func(t *testing.T) {
		fx, ok := readReplyFixture(t, ackUncompressedFixturePath)
		if !ok {
			return
		}
		var ack common.ServerKnockAckMsg
		if err := json.Unmarshal(decryptJsReply(t, fx, NHP_ACK), &ack); err != nil {
			t.Fatalf("unmarshal ack: %v", err)
		}
		if ack.ErrCode != common.ErrSuccess.ErrorCode() {
			t.Errorf("ErrCode = %q, want %q", ack.ErrCode, common.ErrSuccess.ErrorCode())
		}
		if ack.ResourceHost["r_jsagent"] != "10.0.0.7" {
			t.Errorf("ResourceHost[r_jsagent] = %q, want 10.0.0.7", ack.ResourceHost["r_jsagent"])
		}
	})
	t.Run("ack-empty-body", func(t *testing.T) {
		fx, ok := readReplyFixture(t, ackEmptyBodyFixturePath)
		if !ok {
			return
		}
		body := decryptJsReply(t, fx, NHP_ACK)
		if len(body) != 0 {
			t.Errorf("decrypted body length = %d, want 0", len(body))
		}
	})
	t.Run("cok", func(t *testing.T) {
		fx, ok := readReplyFixture(t, cokFixturePath)
		if !ok {
			return
		}
		var cok common.ServerCookieMsg
		if err := json.Unmarshal(decryptJsReply(t, fx, NHP_COK), &cok); err != nil {
			t.Fatalf("unmarshal cok: %v", err)
		}
		if cok.Cookie == "" {
			t.Error("recovered cookie is empty")
		}
		if cok.TransactionId != jsAgentKnockCounter {
			t.Errorf("cookie trxId = %#x, want the knock counter %#x", cok.TransactionId, jsAgentKnockCounter)
		}
	})
}

// TestJsAgentKnockBodyContract fences the TS-built knock body against Go's
// AgentKnockMsg: the field names/values must unmarshal, headerType must be
// NHP_KNK (#1154), and the qURL bootstrap token must stay inside usrData.
func TestJsAgentKnockBodyContract(t *testing.T) {
	raw, err := os.ReadFile(knockBodyFixturePath)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skipf("fixture %s not present (run from the full repo tree)", knockBodyFixturePath)
		}
		t.Fatalf("read %s: %v", knockBodyFixturePath, err)
	}
	var fx struct {
		AuthServiceId   string `json:"authServiceId"`
		ResourceId      string `json:"resourceId"`
		QurlAccessToken string `json:"qurlAccessToken"`
		QurlUserAgent   string `json:"qurlUserAgent"`
		BodyHex         string `json:"bodyHex"`
	}
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("unmarshal fixture: %v", err)
	}
	body, err := hex.DecodeString(fx.BodyHex)
	if err != nil {
		t.Fatalf("decode bodyHex: %v", err)
	}
	var knk common.AgentKnockMsg
	if err := json.Unmarshal(body, &knk); err != nil {
		t.Fatalf("unmarshal AgentKnockMsg from TS body: %v", err)
	}
	if knk.HeaderType != NHP_KNK {
		t.Errorf("HeaderType = %d, want NHP_KNK (%d) — #1154 body-vs-wire invariant", knk.HeaderType, NHP_KNK)
	}
	if knk.AuthServiceId != fx.AuthServiceId {
		t.Errorf("AuthServiceId = %q, want %q (routes the knock to the plugin)", knk.AuthServiceId, fx.AuthServiceId)
	}
	if knk.ResourceId != fx.ResourceId {
		t.Errorf("ResourceId = %q, want %q (bootstrap sentinel for token-carried knocks)", knk.ResourceId, fx.ResourceId)
	}
	gotToken, _ := knk.UserData["qurl_access_token"].(string)
	if gotToken != fx.QurlAccessToken {
		t.Errorf("usrData.qurl_access_token = %q, want %q", gotToken, fx.QurlAccessToken)
	}
	gotUserAgent, _ := knk.UserData["qurl_user_agent"].(string)
	if gotUserAgent != fx.QurlUserAgent {
		t.Errorf("usrData.qurl_user_agent = %q, want %q", gotUserAgent, fx.QurlUserAgent)
	}
}
