# Required public resources retain indexed addresses for state compatibility;
# their constant singleton counts make these outputs non-null.
output "nlb_dns_name" {
  description = "Public cell NLB DNS name for native SDK traffic on UDP 62206."
  value       = one(aws_lb.server[*].dns_name)
}

output "nlb_arn" {
  description = "Public cell NLB ARN."
  value       = one(aws_lb.server[*].arn)
}

output "nlb_arn_suffix" {
  description = "Public cell NLB ARN suffix for CloudWatch."
  value       = one(aws_lb.server[*].arn_suffix)
}

output "nlb_zone_id" {
  description = "Public cell NLB zone ID for Route 53."
  value       = one(aws_lb.server[*].zone_id)
}

# Internal NLB DNS name for the relay -> cell-server UDP hop (#2208 #8 / #2628;
# closes #2626). The root module's `module "relay"` cell_servers[].host points
# here so the relay forwards NHP_RLY to a stable, load-balanced, churn-resilient
# target instead of a once-resolved CloudMap IP. Distinct from `nlb_dns_name`
# (the public, internet-facing NLB used by legacy UDP agents, the resolver, and
# external ACs). This is UDP-only; the in-VPC HTTP token-validation path
# (qurl-service / qurl-reverse-tunnel-server) still uses CloudMap
# `server.<namespace>:8888` and is unaffected.
output "internal_nlb_dns_name" {
  description = "Internal (private) NLB DNS name for the relay -> cell-server UDP knock hop. Points the relay at a stable, load-balanced target that survives server-fleet churn (#2626). Distinct from nlb_dns_name (the public NLB). null when relay_enabled=false (the NLB is gated on it); the consumer (root cell_servers[].host) is likewise gated on deploy_relay, so the null is never dialed."
  value       = one(aws_lb.server_internal[*].dns_name)
}

# CloudWatch dimensions for the internal relay NLB. Null when relay_enabled=false.
output "internal_nlb_arn_suffix" {
  description = "Internal relay NLB ARN suffix for CloudWatch (null when relay not deployed)."
  value       = one(aws_lb.server_internal[*].arn_suffix)
}

output "internal_udp_target_group_arn_suffix" {
  description = "Internal relay UDP target group ARN suffix for CloudWatch (null when relay not deployed)."
  value       = one(aws_lb_target_group.udp_internal[*].arn_suffix)
}

# Full ARN of the BLUE internal relay UDP target group. Null when
# relay_enabled=false.
output "internal_udp_target_group_arn" {
  description = "Blue internal relay UDP target group ARN (null when relay not deployed)."
  value       = one(aws_lb_target_group.udp_internal[*].arn)
}

output "internal_udp_target_group_green_arn" {
  description = "Green internal relay UDP target group ARN (null when relay or blue/green is not enabled)."
  value       = one(aws_lb_target_group.udp_internal_green[*].arn)
}

output "internal_udp_listener_arn" {
  description = "Internal relay UDP listener ARN (null when relay not deployed)."
  value       = one(aws_lb_listener.udp_internal[*].arn)
}

output "asg_name" {
  description = "Auto Scaling Group name"
  value       = aws_autoscaling_group.server.name
}

output "asg_arn" {
  description = "Auto Scaling Group ARN"
  value       = aws_autoscaling_group.server.arn
}

output "server_secret_arn" {
  description = "Server secret ARN"
  value       = aws_secretsmanager_secret.server.arn
}

# The NHP-server identity public key.
#
# Two distinct keypairs operate in this fleet and confusing them
# silently bricks agent-knock validation, so the contract is worth
# spelling out:
#
#   - module.nhp_keypair.registration_public_key — a SHARED keypair
#     used so any AC can register against any NHP-server instance
#     behind the NLB (per modules/nhp-keypair/main.tf:1-8). It is NOT
#     the key NHP-server uses to validate agent knock-packet HMACs.
#   - server_public_key_b64 (this output) — the SERVER-IDENTITY key
#     generated by the keygen Lambda above and stored in Secrets
#     Manager. EVERY in-flight NHP packet (NHP-KNK, NHP-AAK, …) is
#     signed/validated against this key. An agent that constructs its
#     knock with a different pubkey fails server HMAC validation and
#     observes a knock timeout.
#
# Threaded to qurl-service so its /v1/agent/bootstrap response carries
# the value clients need to render server.toml and build knock
# packets the running server can actually validate. Wiring
# `registration_public_key` here instead silently 100%-fails every
# agent boot — see incident notes in
# qurl-reverse-tunnel-client PR #172's tail.
#
# tfstate posture: the underlying `data.aws_secretsmanager_secret_version`
# materializes the FULL secret_string (privateKey + publicKey + hostname
# + environment) into terraform state as a sensitive-marked attribute.
# This is the same posture as the auth0-backend / etcd-tls / cookie-secret
# patterns elsewhere in this tree — tfstate access already implies
# Secrets Manager access via S3+KMS+IAM. The nonsensitive() wrapper
# below is necessary because Terraform propagates the data-source
# sensitivity through jsondecode() / attribute access to the output,
# and a sensitive output value blocks `terraform plan` (since 0.15)
# unless the output marks `sensitive = true` or the value is wrapped
# in nonsensitive(). publicKey IS public by definition; the wrapper
# tells Terraform the propagation no longer applies. It does NOT
# redact the underlying data source — the privateKey still sits in
# state, sensitive-marked. Operators relying on tfstate-as-not-a-
# secret-store must scope state access accordingly.
output "server_public_key_b64" {
  description = "NHP server-identity X25519 public key (standard base64 with `=` padding, 44 chars total — NOT base64url). Threaded into qurl-service so the agent-bootstrap response carries the key clients need for knock-packet HMAC validation. Distinct from module.nhp_keypair.registration_public_key — see the inline comment above for the contract and the tfstate-exposure caveat."
  value       = nonsensitive(try(jsondecode(data.aws_secretsmanager_secret_version.server.secret_string).publicKey, ""))
  # try(..., "") collapses a future drift to an empty string rather
  # than a runtime panic (lambda renames `publicKey` field, partial
  # PutSecretValue, etc.). The empty value still trips the
  # qurl-service module's "non-empty when gate is on" precondition
  # with an actionable message rather than a stack trace.
  sensitive = false
}

output "cloudmap_service_arn" {
  description = "Cloud Map service ARN"
  value       = aws_service_discovery_service.server.arn
}

output "cloudmap_service_dns" {
  description = "Cloud Map DNS name"
  value       = "server.${var.namespace_name}"
}

output "security_group_id" {
  description = "Server security group ID"
  value       = aws_security_group.server.id
}

output "log_group_name" {
  description = "CloudWatch log group name"
  value       = aws_cloudwatch_log_group.server.name
}

output "log_group_stderr_name" {
  description = "CloudWatch log group name for container stdout/stderr (panics, runtime errors, EMF metric emissions). Consumed by the monitoring module: a metric filter drives the ServerPanic alarm, and CloudWatch auto-extracts ServerStartupEvent from EMF JSON lines emitted by the Go server at startup (#1107)."
  value       = aws_cloudwatch_log_group.server_stderr.name
}

output "target_group_arn_suffix" {
  description = "Public UDP target group ARN suffix for CloudWatch."
  value       = one(aws_lb_target_group.udp[*].arn_suffix)
}

output "https_target_group_arn_suffix" {
  description = "HTTPS target group ARN suffix for CloudWatch (null if QURL resolve endpoint not enabled)"
  value       = var.enable_qurl_resolve_endpoint ? aws_lb_target_group.https[0].arn_suffix : null
}

output "https_green_target_group_arn_suffix" {
  description = "Green HTTPS target group ARN suffix for CloudWatch (null if blue/green disabled or QURL resolve endpoint not enabled)"
  value       = var.enable_blue_green && var.enable_qurl_resolve_endpoint ? aws_lb_target_group.https_green[0].arn_suffix : null
}

# =============================================================================
# SSM Parameter Outputs for CI/CD
# =============================================================================

output "ssm_image_tag_parameter" {
  description = "SSM parameter name for the deployed image tag"
  value       = aws_ssm_parameter.image_tag.name
}

output "ssm_asg_name_parameter" {
  description = "SSM parameter name for the ASG name"
  value       = aws_ssm_parameter.asg_name.name
}

output "ssm_deployed_commit_parameter" {
  description = "SSM parameter name for deployed commit SHA"
  value       = aws_ssm_parameter.deployed_commit.name
}

output "ssm_deployed_at_parameter" {
  description = "SSM parameter name for deployment timestamp"
  value       = aws_ssm_parameter.deployed_at.name
}

# =============================================================================
# NLB Outputs for Blue/Green Deployment (Phase 2)
# =============================================================================

output "nlb_udp_listener_arn" {
  description = "Public NLB UDP listener ARN used for blue/green traffic switching."
  value       = one(aws_lb_listener.udp[*].arn)
}

output "target_group_arn" {
  description = "Public UDP target group ARN."
  value       = one(aws_lb_target_group.udp[*].arn)
}

# =============================================================================
# Blue/Green Deployment Outputs
# =============================================================================

output "blue_green_enabled" {
  description = "Whether blue/green deployment infrastructure is enabled"
  value       = var.enable_blue_green
}

output "green_asg_name" {
  description = "Green Auto Scaling Group name (null if blue/green not enabled)"
  value       = var.enable_blue_green ? aws_autoscaling_group.server_green[0].name : null
}

output "green_asg_arn" {
  description = "Green Auto Scaling Group ARN (null if blue/green not enabled)"
  value       = var.enable_blue_green ? aws_autoscaling_group.server_green[0].arn : null
}

output "udp_target_group_blue_arn" {
  description = "Blue public UDP target group ARN (same as target_group_arn)."
  value       = one(aws_lb_target_group.udp[*].arn)
}

output "udp_target_group_green_arn" {
  description = "Green public UDP target group ARN (null if blue/green is not enabled)."
  value       = one(aws_lb_target_group.udp_green[*].arn)
}

output "https_target_group_blue_arn" {
  description = "Blue HTTPS target group ARN (null if QURL resolve endpoint not enabled)"
  value       = var.enable_qurl_resolve_endpoint ? aws_lb_target_group.https[0].arn : null
}

output "https_target_group_green_arn" {
  description = "Green HTTPS target group ARN (null if blue/green or QURL resolve not enabled)"
  value       = var.enable_blue_green && var.enable_qurl_resolve_endpoint ? aws_lb_target_group.https_green[0].arn : null
}

output "nlb_https_listener_arn" {
  description = "NLB HTTPS listener ARN (null if QURL resolve endpoint not enabled)"
  value       = var.enable_qurl_resolve_endpoint ? aws_lb_listener.https[0].arn : null
}

output "ssm_active_color_parameter" {
  description = "SSM parameter name for active deployment color (null if blue/green not enabled)"
  value       = var.enable_blue_green ? aws_ssm_parameter.active_color[0].name : null
}

output "ssm_green_image_tag_parameter" {
  description = "SSM parameter name for green ASG image tag (null if blue/green not enabled)"
  value       = var.enable_blue_green ? aws_ssm_parameter.green_image_tag[0].name : null
}

output "ssm_green_asg_name_parameter" {
  description = "SSM parameter name for green ASG name (null if blue/green not enabled)"
  value       = var.enable_blue_green ? aws_ssm_parameter.green_asg_name[0].name : null
}

# =============================================================================
# Launch Template Outputs
# =============================================================================

output "launch_template_arn" {
  description = "Server launch template ARN (for canary deployment IAM)"
  value       = aws_launch_template.server.arn
}
