# Generated by Terraform (#2208 5c). With DisableRelayValidation=true the server
# authenticates the relay by pubkey (HandleRelayForward.lookupRelayPeer) and
# replies the ACK to the learned recv address, so Ip/Port/ExpireTime are all INERT
# — PubKeyBase64 is the only load-bearing field. The rest are valid-but-unused
# placeholders (RFC 5737 TEST-NET-3 Ip, far-future ExpireTime).
#
# Flipping DisableRelayValidation OFF is NOT a config-only change: with validation
# on, CheckRecvAddress would pin the source to this placeholder Ip (and IsExpired
# would gate on ExpireTime), rejecting real traffic. The shared-keypair multi-IP
# fleet can't be a single pinned Ip anyway, so validation-on needs a different
# registration model (dynamic registry, #2541), not a flag toggle.
%{ for relay_pubkey in relay_trusted_public_keys_b64 ~}
[[Relays]]
Ip = "203.0.113.50"
Port = 62206
PubKeyBase64 = "${relay_pubkey}"
ExpireTime = 1924991999
%{ endfor ~}
