# NHP-Relay module (#2208 Phase-2 #5).
#
# Stands up the internet-facing relay: an autoscaling fleet (one instance per AZ
# baseline) behind an ALB that forwards a browser's opaque NHP knock to the
# (private) cell server. The shared-keypair fleet authenticates by Noise pubkey +
# relay.toml registration, not source IP (server DisableRelayPeerValidation; 5c).
# Ships DARK — until 5c registers the relay's pubkey in the server's relay.toml,
# every NHP_RLY is rejected at the server's Noise layer (the relay is not yet a
# registered peer), so `POST /relay/{id}` returns 504. The relay boots,
# `/health/live` is 200, and the ALB is internet-reachable, but it can't pivot
# into the private network until 5c lights it up. See
# docs/design/NHP_RELAY_TOPOLOGY.md.

data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

# AMI: default to the SSM-published server AMI (Docker + awscli + the
# systemd-resolved stub-disable fix the relay's startup CloudMap resolve needs).
# A stock Ubuntu AMI would crash-loop on `net.ResolveUDPAddr` against the
# systemd-resolved stub — see variable.server_ami_id.
data "aws_ssm_parameter" "server_ami" {
  count = var.server_ami_id == null ? 1 : 0
  name  = "/${var.environment}/nhp/server/ami-id"
}

locals {
  is_prod = var.environment == "prod"

  ami_id = var.server_ami_id != null ? var.server_ami_id : data.aws_ssm_parameter.server_ami[0].value

  tags = merge(var.tags, {
    Environment = var.environment
    Component   = "relay"
  })

  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    region                  = data.aws_region.current.id
    environment             = var.environment
    relay_repo_url          = var.relay_repo_url
    secret_arn              = aws_secretsmanager_secret.relay.arn
    ssm_image_tag_parameter = aws_ssm_parameter.image_tag.name
    log_group               = aws_cloudwatch_log_group.relay.name
    # relay.toml render inputs
    listen_port     = var.listen_port
    udp_listen_port = var.udp_listen_port
    cell_servers    = var.cell_servers
  })
}

# ============================================================================
# Relay keypair (one per fleet; #2208). Generated by an inline X25519 keygen
# Lambda into Secrets Manager — same generator as the server keypair
# (modules/compute), self-contained here so the relay module has no cross-module
# coupling. X25519 == Curve25519 (the relay's `nhp-relayd keygen` curve).
# ============================================================================

resource "aws_iam_role" "keygen_lambda" {
  name = "${var.name_prefix}-relay-keygen-lambda"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
    }]
  })

  tags = local.tags
}

resource "aws_iam_role_policy_attachment" "keygen_lambda_basic" {
  role       = aws_iam_role.keygen_lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_iam_role_policy" "keygen_lambda_secrets" {
  name = "secrets-access"
  role = aws_iam_role.keygen_lambda.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = concat([
      {
        Effect   = "Allow"
        Action   = ["secretsmanager:GetSecretValue", "secretsmanager:PutSecretValue"]
        Resource = [aws_secretsmanager_secret.relay.arn]
      }
      ],
      # KMS only when the secret uses a customer-managed key (null = AWS-managed,
      # no explicit grant) — omit rather than render Resource=[] (malformed IAM).
      var.secrets_kms_key_arn != null ? [
        {
          Effect   = "Allow"
          Action   = ["kms:Encrypt", "kms:Decrypt", "kms:GenerateDataKey"]
          Resource = [var.secrets_kms_key_arn]
        }
    ] : [])
  })
}

data "archive_file" "keygen_lambda" {
  type        = "zip"
  output_path = "${path.module}/relay_keygen_lambda.zip"

  source {
    content  = <<-EOF
const crypto = require('crypto');
const { SecretsManagerClient, GetSecretValueCommand, PutSecretValueCommand } = require('@aws-sdk/client-secrets-manager');

exports.handler = async (event) => {
  // aws_lambda_invocation only fires on create/input-change (input hardcodes
  // RequestType=Create); no delete-event branch is needed (unlike the CFN
  // custom-resource idiom modules/compute carries).
  console.log('RequestType:', event.RequestType);

  const client = new SecretsManagerClient({});
  const secretId = event.ResourceProperties.SecretId;
  const environment = event.ResourceProperties.Environment;

  // Idempotent: never overwrite an existing valid keypair (rotating the relay
  // key out from under the server's relay.toml registration would break auth).
  try {
    const existing = await client.send(new GetSecretValueCommand({ SecretId: secretId }));
    if (existing.SecretString) {
      const parsed = JSON.parse(existing.SecretString);
      if (parsed.privateKey && parsed.privateKey.length === 44 && parsed.publicKey && parsed.publicKey.length === 44) {
        console.log('Relay secret already has a valid key pair, not overwriting');
        return { PhysicalResourceId: event.PhysicalResourceId || secretId };
      }
    }
  } catch (e) {
    console.log('No existing relay secret value, will create new');
  }

  const keyPair = crypto.generateKeyPairSync('x25519');
  const privateKeyRaw = keyPair.privateKey.export({ type: 'pkcs8', format: 'der' });
  const publicKeyRaw = keyPair.publicKey.export({ type: 'spki', format: 'der' });
  const privateKeyBase64 = privateKeyRaw.slice(-32).toString('base64');
  const publicKeyBase64 = publicKeyRaw.slice(-32).toString('base64');

  await client.send(new PutSecretValueCommand({
    SecretId: secretId,
    SecretString: JSON.stringify({ privateKey: privateKeyBase64, publicKey: publicKeyBase64, environment }),
  }));
  console.log('Generated new relay key pair, publicKey:', publicKeyBase64);
  return { PhysicalResourceId: event.PhysicalResourceId || secretId };
};
EOF
    filename = "index.js"
  }
}

resource "aws_lambda_function" "keygen" {
  function_name = "${var.name_prefix}-relay-keygen"
  role          = aws_iam_role.keygen_lambda.arn
  handler       = "index.handler"
  runtime       = "nodejs22.x"
  timeout       = 30

  filename         = data.archive_file.keygen_lambda.output_path
  source_code_hash = data.archive_file.keygen_lambda.output_base64sha256

  tags = local.tags
}

resource "aws_secretsmanager_secret" "relay" {
  name                    = "${var.name_prefix}-relay"
  description             = "NHP Relay fleet private key (one keypair per env; #2208)"
  recovery_window_in_days = local.is_prod ? 30 : 0
  kms_key_id              = var.secrets_kms_key_arn

  tags = merge(local.tags, { Name = "${var.name_prefix}-relay-secret" })
}

resource "aws_lambda_invocation" "keygen" {
  function_name = aws_lambda_function.keygen.function_name

  input = jsonencode({
    RequestType = "Create"
    ResourceProperties = {
      SecretId    = aws_secretsmanager_secret.relay.id
      Environment = var.environment
    }
  })

  depends_on = [aws_iam_role_policy.keygen_lambda_secrets]

  lifecycle {
    ignore_changes = [input]
  }
}

# Read back the generated publicKey so outputs.tf can thread it to 5c.
# tfstate posture matches modules/compute's server-key data source: the full
# secret_string materializes sensitive-marked in state; only the public key is
# nonsensitive()-surfaced.
data "aws_secretsmanager_secret_version" "relay" {
  secret_id     = aws_secretsmanager_secret.relay.id
  version_stage = "AWSCURRENT"
  depends_on    = [aws_lambda_invocation.keygen]
}
