#!/bin/bash
# NHP-Relay node bootstrap (#2208). Runs on the server AMI (Docker + awscli +
# the systemd-resolved stub-disable fix the relay's startup CloudMap resolve
# needs). Pulls the relay image, renders relay.toml from the fleet keypair, and
# runs nhp-relayd as a systemd-managed container on the HOST network (so the
# relay's UDP source address — which the server pins via CheckRecvAddress — is
# the instance IP, not a docker-NAT address, and the server's ACK returns to it).
set -ex
exec > >(tee /var/log/user-data.log | logger -t user-data) 2>&1
echo "Starting NHP-Relay installation at $(date)"

REGION="${region}"

report_failure() {
  echo "BOOTSTRAP FAILED: $1"
  command -v aws &>/dev/null && aws cloudwatch put-metric-data \
    --namespace "LayerV/NHP" \
    --metric-name "BootstrapFailure" \
    --value 1 --unit Count \
    --dimensions "Component=relay,Environment=${environment}" \
    --region "$REGION" 2>/dev/null || true
}
# Guarded fatal: emit the BootstrapFailure metric on the explicit-exit paths the
# ERR trap can't see (||-guarded commands, [ -z ] checks — the likeliest boot
# failures). set -x first so the failure trace lands even when called from inside
# a set +x secret block; the message is a static string (no secret).
fatal() {
  set -x
  report_failure "$1"
  exit 1
}
trap 'report_failure "unexpected error on line $LINENO"' ERR

# Docker is pre-baked into the server AMI; ensure the daemon is up.
systemctl enable docker
systemctl start docker || true
for _ in $(seq 1 30); do docker info >/dev/null 2>&1 && break || sleep 2; done

# Instance id for the awslogs stream name (region is templated in above).
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
INSTANCE_ID=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)
if [ -z "$INSTANCE_ID" ]; then
  fatal "IMDS returned empty instance-id; cannot continue"
fi

# ECR login (handles cross-account: registry domain is the repo URL's host).
ECR_REPO="${relay_repo_url}"
ECR_REGISTRY="$(echo "$ECR_REPO" | cut -d/ -f1)"
aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"

# Image tag from SSM (CI source of truth; see modules/relay/compute.tf).
SSM_IMAGE_TAG_PARAM="${ssm_image_tag_parameter}"
IMAGE_TAG=$(aws ssm get-parameter --name "$SSM_IMAGE_TAG_PARAM" --region "$REGION" --query "Parameter.Value" --output text) ||
  fatal "failed to fetch relay image tag from SSM ($SSM_IMAGE_TAG_PARAM)"
if [ -z "$IMAGE_TAG" ] || [ "$IMAGE_TAG" = "None" ] || [ "$IMAGE_TAG" = "initial" ]; then
  fatal "SSM parameter $SSM_IMAGE_TAG_PARAM has no valid image tag (got '$IMAGE_TAG')"
fi
echo "Using relay image tag from SSM: $IMAGE_TAG"

docker pull "$ECR_REPO:$IMAGE_TAG" ||
  fatal "could not pull relay image $ECR_REPO:$IMAGE_TAG"

# ── relay.toml ──
# Pinned uid:gid for the non-root relay container (#1090). The mounted
# relay.toml carries the fleet private key, so create the inode + chmod 600 +
# chown to the runtime uid BEFORE the secret lands, then keep the heredoc body
# off xtrace (bash does not trace heredoc bodies; the private-key fetch below is
# bracketed with set +x).
RELAY_UID=10001
RELAY_GID=10001
mkdir -p /opt/layerv/nhp-relay/etc
touch /opt/layerv/nhp-relay/etc/relay.toml
chmod 600 /opt/layerv/nhp-relay/etc/relay.toml
chown "$RELAY_UID:$RELAY_GID" /opt/layerv/nhp-relay/etc/relay.toml

# SECURITY: the relay private key is the fleet-wide NHP_RELAY identity. Under
# set -x the `SECRET=$(aws ...)` assignment and the jq pipe would trace it into
# user-data.log → CloudWatch. Bracket fetch + extract with set +x, scrub $SECRET.
set +x
SECRET=$(aws secretsmanager get-secret-value --secret-id "${secret_arn}" --region "$REGION" --query SecretString --output text) ||
  fatal "could not fetch relay secret from Secrets Manager"
PRIVATE_KEY=$(echo "$SECRET" | jq -er ".privateKey") ||
  fatal "could not extract privateKey from relay secret JSON (missing or null)"
unset SECRET
set -x

# `>` truncates the existing inode in place — it preserves the chmod 600 + chown
# set above, so the fleet private key never lands at the default cloud-init umask.
cat > /opt/layerv/nhp-relay/etc/relay.toml << CONFIGEOF
# Generated by Terraform (modules/relay/user_data.sh.tpl).
listen_addr = ":${listen_port}"
udp_listen_addr = "0.0.0.0:${udp_listen_port}"
private_key = "$PRIVATE_KEY"
# Behind the TLS-terminating ALB, which APPENDS the real client IP to the END of
# X-Forwarded-For (so the RIGHTMOST entry is the ALB-attested IP) and is the only
# path to the relay (relay SG ingress = ALB only). The relay reads this header for
# the AC-pinhole client IP — it MUST take the rightmost entry, not the leftmost
# (a client can pre-seed a spoofed leftmost value); the rightmost parse is #2622.
source_addr_mode = "trusted_header"
trusted_header = "X-Forwarded-For"
enable_tls = false
%{ for s in cell_servers ~}

[[servers]]
name = "${s.name}"
public_key = "${s.public_key}"
host = "${s.host}"
port = ${s.port}
%{ endfor ~}
CONFIGEOF
unset PRIVATE_KEY

# ── systemd unit ──
# --network host: the relay's UDP socket binds the instance network directly, so
#   its source address is stable + server-reachable (CheckRecvAddress pin).
# --user: non-root runtime (#1090); the relay binds >1024 and needs no caps. The
#   mounted relay.toml is chowned to this uid above so the container can read it.
# --log-driver awslogs: stdout/stderr → CloudWatch (the instance role grants
#   CreateLogStream/PutLogEvents on the group).
cat > /etc/systemd/system/nhp-relayd.service << SVCEOF
[Unit]
Description=NHP-Relay daemon (#2208)
After=network-online.target docker.service
Wants=network-online.target
Requires=docker.service

[Service]
Restart=always
RestartSec=5
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker rm -f nhp-relay
ExecStart=/usr/bin/docker run --rm --name nhp-relay \\
  --network host \\
  --user $RELAY_UID:$RELAY_GID \\
  -v /opt/layerv/nhp-relay/etc/relay.toml:/nhp-relay/etc/relay.toml:ro \\
  --log-driver=awslogs \\
  --log-opt awslogs-region=${region} \\
  --log-opt awslogs-group=${log_group} \\
  --log-opt awslogs-stream=$INSTANCE_ID/relay \\
  $ECR_REPO:$IMAGE_TAG run
ExecStop=/usr/bin/docker stop nhp-relay

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable nhp-relayd.service
systemctl start nhp-relayd.service
echo "NHP-Relay started with image tag: $IMAGE_TAG"
