#!/bin/bash
# Custom Domain Certificate Sync
# Fetches ALL active custom domain certs from Secrets Manager
# and rebuilds /home/ubuntu/traefik/custom-domains.toml
#
# Triggered by:
# - Custom Domain Cert Lambda (after provisioning/renewal)
# - AC instance boot (user_data.sh)
# - 6-hourly SSM association
set -euo pipefail

SECRETS_PREFIX="${SECRETS_PREFIX:-custom-domain-cert}"
TRAEFIK_DIR="${TRAEFIK_DIR:-/home/ubuntu/traefik}"
CERT_DIR="${TRAEFIK_DIR}/certs/custom-domains"
CONFIG_FILE="${TRAEFIK_DIR}/custom-domains.toml"
REGION="${AWS_REGION:-us-east-2}"

echo "Starting custom domain certificate sync at $(date)"

# Ensure snap binaries are in PATH (for AWS CLI)
export PATH="/snap/bin:$PATH"

# Create directories
mkdir -p "$CERT_DIR"

# List all custom domain cert secrets
echo "Listing custom domain certificates..."
SECRETS=$(aws secretsmanager list-secrets \
  --region "$REGION" \
  --filters Key=name,Values="$SECRETS_PREFIX/" \
  --query 'SecretList[].Name' \
  --output text 2>/dev/null || echo "")

if [ -z "$SECRETS" ]; then
    echo "No custom domain certificates found"
    # Write empty config file
    echo "# No custom domains configured" > "$CONFIG_FILE"
    chown ubuntu:ubuntu "$CONFIG_FILE"
    echo "Done"
    exit 0
fi

# Start building new config
TEMP_CONFIG=$(mktemp)
CERT_TEMP=""
trap 'rm -f "$TEMP_CONFIG" "$CERT_TEMP" 2>/dev/null' EXIT
echo "# Custom Domain Traefik Configuration" > "$TEMP_CONFIG"
echo "# Auto-generated by custom-domain-cert-sync.sh at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$TEMP_CONFIG"
echo "# DO NOT EDIT MANUALLY" >> "$TEMP_CONFIG"
echo "" >> "$TEMP_CONFIG"

DOMAIN_COUNT=0
FAILED_COUNT=0
ACTIVE_DOMAINS=""

for SECRET_NAME in $SECRETS; do
    # Extract domain from secret name (prefix/domain.com -> domain.com)
    DOMAIN="${SECRET_NAME#${SECRETS_PREFIX}/}"

    if [ -z "$DOMAIN" ]; then
        echo "WARNING: Empty domain from secret $SECRET_NAME, skipping"
        continue
    fi

    # Validate domain is DNS-safe before using in TOML config
    if ! [[ "$DOMAIN" =~ ^[a-zA-Z0-9]([a-zA-Z0-9.-]{0,251}[a-zA-Z0-9])?$ ]]; then
        echo "WARNING: Invalid domain name format: $DOMAIN, skipping"
        continue
    fi

    # Reject path traversal sequences
    if [[ "$DOMAIN" == *".."* ]]; then
        echo "WARNING: Invalid domain path (contains '..'): $DOMAIN, skipping"
        continue
    fi

    # Reject wildcard domains — redundant with regex above (which excludes *)
    # but kept for a clearer log message when debugging.
    if [[ "$DOMAIN" == *"*"* ]]; then
        echo "WARNING: Wildcard domains not supported: $DOMAIN, skipping"
        continue
    fi

    echo "Processing certificate for: $DOMAIN"

    # Create domain cert directory
    DOMAIN_CERT_DIR="$CERT_DIR/$DOMAIN"
    mkdir -p "$DOMAIN_CERT_DIR"

    # Fetch cert from Secrets Manager (retry with backoff for rate limiting)
    CERT_TEMP=$(mktemp)
    FETCH_OK=false
    for RETRY in 1 2 3; do
        if aws secretsmanager get-secret-value \
            --region "$REGION" \
            --secret-id "$SECRET_NAME" \
            --query SecretString --output text > "$CERT_TEMP" 2>/dev/null; then
            FETCH_OK=true
            break
        fi
        [ "$RETRY" -lt 3 ] && sleep "$((RETRY * 2))"
    done
    if [ "$FETCH_OK" != "true" ]; then
        echo "WARNING: Failed to fetch cert for $DOMAIN after 3 attempts, skipping"
        rm -f "$CERT_TEMP"
        FAILED_COUNT=$((FAILED_COUNT + 1))
        continue
    fi

    # Validate and extract cert data in a single jq pass
    PARSED=$(jq -r '
      if .certificate == null then "ERR_NO_CERT"
      elif .private_key == null then "ERR_NO_KEY"
      elif .status == "pending" then "ERR_PENDING"
      else (.fullchain // .certificate) + "\n===SPLIT===\n" + .private_key
      end
    ' "$CERT_TEMP" 2>/dev/null) || PARSED="ERR_INVALID_JSON"
    rm -f "$CERT_TEMP"

    case "$PARSED" in
        ERR_INVALID_JSON)
            echo "WARNING: Invalid JSON for $DOMAIN, skipping"
            FAILED_COUNT=$((FAILED_COUNT + 1)); continue ;;
        ERR_NO_CERT)
            echo "WARNING: Invalid cert data for $DOMAIN (missing certificate field), skipping"
            FAILED_COUNT=$((FAILED_COUNT + 1)); continue ;;
        ERR_NO_KEY)
            echo "WARNING: Invalid cert data for $DOMAIN (missing private_key field), skipping"
            FAILED_COUNT=$((FAILED_COUNT + 1)); continue ;;
        ERR_PENDING)
            echo "WARNING: Certificate for $DOMAIN is still pending, skipping"
            continue ;;
    esac

    # Split extracted data into cert and key files
    echo "$PARSED" | awk '/===SPLIT===/{found=1; next} !found' > "$DOMAIN_CERT_DIR/fullchain.pem"
    echo "$PARSED" | awk '/===SPLIT===/{found=1; next} found' > "$DOMAIN_CERT_DIR/privkey.pem"

    # Set permissions and ownership
    chmod 600 "$DOMAIN_CERT_DIR/privkey.pem"
    chmod 644 "$DOMAIN_CERT_DIR/fullchain.pem"
    chown ubuntu:ubuntu "$DOMAIN_CERT_DIR/privkey.pem" "$DOMAIN_CERT_DIR/fullchain.pem"

    # Verify cert is not expired and extract expiry date (single openssl call)
    CERT_INFO=$(openssl x509 -in "$DOMAIN_CERT_DIR/fullchain.pem" -noout -checkend 0 -enddate 2>/dev/null) || {
        echo "WARNING: Certificate for $DOMAIN is expired or invalid, skipping"
        FAILED_COUNT=$((FAILED_COUNT + 1))
        continue
    }
    CERT_EXPIRY=$(echo "$CERT_INFO" | grep '^notAfter=' | cut -d= -f2)

    # Verify private key matches certificate (catches corrupted secrets).
    # Commands are separated (not piped) so failures are caught individually
    # under set -euo pipefail instead of aborting the entire script.
    CERT_MOD=$(openssl x509 -noout -modulus -in "$DOMAIN_CERT_DIR/fullchain.pem" 2>/dev/null) || {
        echo "WARNING: Cannot read certificate modulus for $DOMAIN, skipping"
        FAILED_COUNT=$((FAILED_COUNT + 1))
        continue
    }
    KEY_MOD=$(openssl rsa -noout -modulus -in "$DOMAIN_CERT_DIR/privkey.pem" 2>/dev/null) || {
        echo "WARNING: Cannot read private key modulus for $DOMAIN, skipping"
        FAILED_COUNT=$((FAILED_COUNT + 1))
        continue
    }
    if [ "$CERT_MOD" != "$KEY_MOD" ]; then
        echo "WARNING: Certificate/key mismatch for $DOMAIN, skipping"
        FAILED_COUNT=$((FAILED_COUNT + 1))
        continue
    fi

    # Sanitize domain for TOML key (replace dots with dashes)
    TOML_KEY=$(echo "$DOMAIN" | tr '.' '-')

    # Append router + TLS config for this domain
    cat >> "$TEMP_CONFIG" << DOMAINEOF

[http.routers.custom-${TOML_KEY}]
  rule = "Host(\`${DOMAIN}\`)"
  service = "qurl-backend"
  entryPoints = ["https"]
  priority = 25
  middlewares = ["qurl-router"]
  [http.routers.custom-${TOML_KEY}.tls]

[[tls.certificates]]
  certFile = "${DOMAIN_CERT_DIR}/fullchain.pem"
  keyFile = "${DOMAIN_CERT_DIR}/privkey.pem"

DOMAINEOF

    ACTIVE_DOMAINS="$ACTIVE_DOMAINS $DOMAIN"
    DOMAIN_COUNT=$((DOMAIN_COUNT + 1))
    echo "  Certificate loaded, expires: $CERT_EXPIRY"
done

# Remove stale cert directories for domains no longer in Secrets Manager
if [ -d "$CERT_DIR" ]; then
    for DIR in "$CERT_DIR"/*/; do
        [ -d "$DIR" ] || continue
        DIR_DOMAIN=$(basename "$DIR")
        if ! echo "$ACTIVE_DOMAINS" | grep -Fwq "$DIR_DOMAIN"; then
            echo "Removing stale cert directory for: $DIR_DOMAIN"
            rm -rf "$DIR"
        fi
    done
fi

# Set ownership and permissions before atomic replace so Traefik
# never sees incorrect ownership between mv and chown.
chmod 644 "$TEMP_CONFIG"
chown ubuntu:ubuntu "$TEMP_CONFIG"
if ! mv "$TEMP_CONFIG" "$CONFIG_FILE"; then
    echo "ERROR: Failed to update config file"
    exit 1
fi

echo ""
echo "============================================"
echo "Custom domain cert sync complete"
echo "  Domains loaded: $DOMAIN_COUNT"
echo "  Failures: $FAILED_COUNT"
echo "============================================"

# Publish sync metrics to CloudWatch for operational visibility
METRICS_OUTPUT=$(aws cloudwatch put-metric-data \
  --namespace "NHP/CustomDomainCerts" \
  --metric-data "[{\"MetricName\":\"CertSyncDomainsLoaded\",\"Value\":$DOMAIN_COUNT,\"Unit\":\"Count\"},{\"MetricName\":\"CertSyncFailures\",\"Value\":$FAILED_COUNT,\"Unit\":\"Count\"}]" \
  --region "$REGION" 2>&1) || echo "WARNING: Failed to publish CloudWatch metrics: $METRICS_OUTPUT"

# Traefik file provider is configured with watch=true in user_data.sh.tpl
# (providers.file.directory + watch = true), so it automatically picks up
# changes to custom-domains.toml. No restart needed.
