#!/usr/bin/env bash
# Local fixture test for custom-domain-cert-sync.sh --delete mode (#1994).
#
# Runs in a tmp dir, no AWS calls, no sudo. Designed to be runnable on a dev
# laptop and in CI (lint workflow). Not a smoke test — that's tests/smoke/.
#
# Invocation:
#   bash terraform/modules/ac/scripts/test-cert-sync-delete.sh
#
# The AC script chowns its outputs to ubuntu:ubuntu and calls `aws cloudwatch`.
# Both would explode on a dev box, so we override them via PATH shim.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET_SCRIPT="${SCRIPT_DIR}/custom-domain-cert-sync.sh"

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT

SHIM_DIR="$WORKDIR/shims"
mkdir -p "$SHIM_DIR"

# Override chown to a no-op (would require root for ubuntu:ubuntu locally).
cat > "$SHIM_DIR/chown" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
chmod +x "$SHIM_DIR/chown"

# Track aws invocations to fence "delete mode does not consult SSM" and
# captures the cloudwatch put-metric-data we DO expect.
AWS_CALLS="$WORKDIR/aws-calls.log"
cat > "$SHIM_DIR/aws" <<EOF
#!/usr/bin/env bash
echo "\$@" >> "$AWS_CALLS"
exit 0
EOF
chmod +x "$SHIM_DIR/aws"

export PATH="$SHIM_DIR:$PATH"
export TRAEFIK_DIR="$WORKDIR/traefik"
export AWS_REGION="us-east-2"

CERT_DIR="$TRAEFIK_DIR/certs/custom-domains"
CONFIG_FILE="$TRAEFIK_DIR/custom-domains.toml"

# --- Fixture: two domains, two TOML blocks ----------------------------------
mkdir -p "$CERT_DIR/a.example.com" "$CERT_DIR/b.example.com"
echo "fake-fullchain-a" > "$CERT_DIR/a.example.com/fullchain.pem"
echo "fake-key-a" > "$CERT_DIR/a.example.com/privkey.pem"
echo "fake-fullchain-b" > "$CERT_DIR/b.example.com/fullchain.pem"
echo "fake-key-b" > "$CERT_DIR/b.example.com/privkey.pem"

mkdir -p "$TRAEFIK_DIR"
cat > "$CONFIG_FILE" <<EOF
# Custom Domain Traefik Configuration
# Auto-generated by custom-domain-cert-sync.sh

[[tls.certificates]]
  certFile = "$CERT_DIR/a.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/a.example.com/privkey.pem"

[[tls.certificates]]
  certFile = "$CERT_DIR/b.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/b.example.com/privkey.pem"
EOF

PASS=0
FAIL=0
log() { echo "[test-cert-sync-delete] $*"; }
assert_eq() {
    local expected="$1" actual="$2" desc="$3"
    if [[ "$expected" == "$actual" ]]; then
        log "PASS: $desc"
        PASS=$((PASS + 1))
    else
        log "FAIL: $desc"
        log "  expected: $expected"
        log "  actual:   $actual"
        FAIL=$((FAIL + 1))
    fi
}
assert_present() {
    local pattern="$1" file="$2" desc="$3"
    if grep -Fq "$pattern" "$file"; then
        log "PASS: $desc"
        PASS=$((PASS + 1))
    else
        log "FAIL: $desc (pattern not in $file)"
        log "  pattern: $pattern"
        FAIL=$((FAIL + 1))
    fi
}
assert_absent() {
    local pattern="$1" file="$2" desc="$3"
    if grep -Fq "$pattern" "$file" 2>/dev/null; then
        log "FAIL: $desc (pattern still in $file)"
        log "  pattern: $pattern"
        FAIL=$((FAIL + 1))
    else
        log "PASS: $desc"
        PASS=$((PASS + 1))
    fi
}

# --- Test 1: delete a.example.com leaves b.example.com intact ---------------
log "Test 1: delete one of two domains"
bash "$TARGET_SCRIPT" --delete a.example.com > "$WORKDIR/t1.out" 2>&1 || {
    log "FAIL: --delete a.example.com exited non-zero"
    cat "$WORKDIR/t1.out"
    exit 1
}
if [[ -d "$CERT_DIR/a.example.com" ]]; then
    assert_eq "removed" "still present" "a.example.com dir removed"
else
    assert_eq "ok" "ok" "a.example.com dir removed"
fi
if [[ -d "$CERT_DIR/b.example.com" ]]; then
    assert_eq "ok" "ok" "b.example.com dir preserved"
else
    assert_eq "preserved" "removed" "b.example.com dir preserved"
fi
assert_absent "a.example.com/fullchain.pem" "$CONFIG_FILE" "TOML block for a.example.com removed"
assert_present "b.example.com/fullchain.pem" "$CONFIG_FILE" "TOML block for b.example.com preserved"

# Verify the metric was published (cloudwatch put-metric-data) and SSM
# was NOT consulted (no get-parameter / get-parameters-by-path).
assert_present "cloudwatch put-metric-data" "$AWS_CALLS" "CloudWatch metric published"
assert_present "CertSyncDomainsRemoved" "$AWS_CALLS" "CertSyncDomainsRemoved metric name emitted"
assert_absent "ssm get-parameter" "$AWS_CALLS" "delete mode did not consult SSM"

# --- Test 2: re-run is idempotent -------------------------------------------
log "Test 2: re-run is idempotent (domain already gone)"
bash "$TARGET_SCRIPT" --delete a.example.com > "$WORKDIR/t2.out" 2>&1 || {
    log "FAIL: --delete on absent domain exited non-zero"
    cat "$WORKDIR/t2.out"
    exit 1
}
assert_present "already absent" "$WORKDIR/t2.out" "logged 'already absent' on re-run"
if [[ -d "$CERT_DIR/b.example.com" ]]; then
    assert_eq "ok" "ok" "b.example.com dir still preserved after re-run"
else
    assert_eq "preserved" "removed" "b.example.com dir still preserved after re-run"
fi
# Re-run should NOT publish CertSyncDomainsRemoved a second time — that
# metric is the offboarding-distinct counter. The dedup branch must
# publish CertSyncDomainAlreadyAbsent so operators can tell SNS retries
# apart from genuine offboards. (cr round 1 on #2005.)
assert_present "CertSyncDomainAlreadyAbsent" "$AWS_CALLS" "re-run published CertSyncDomainAlreadyAbsent (dedup distinct from offboard)"

# --- Test 3: invalid domain refused -----------------------------------------
log "Test 3: invalid domain rejected with non-zero exit"
if bash "$TARGET_SCRIPT" --delete "../../etc/passwd" > "$WORKDIR/t3.out" 2>&1; then
    log "FAIL: traversal domain unexpectedly accepted"
    FAIL=$((FAIL + 1))
else
    log "PASS: traversal domain rejected"
    PASS=$((PASS + 1))
fi
if bash "$TARGET_SCRIPT" --delete "*.example.com" > "$WORKDIR/t3b.out" 2>&1; then
    log "FAIL: wildcard domain unexpectedly accepted"
    FAIL=$((FAIL + 1))
else
    log "PASS: wildcard domain rejected"
    PASS=$((PASS + 1))
fi

# --- Test 4: missing config_file does not error -----------------------------
log "Test 4: missing config_file is tolerated"
rm -f "$CONFIG_FILE"
mkdir -p "$CERT_DIR/c.example.com"
bash "$TARGET_SCRIPT" --delete c.example.com > "$WORKDIR/t4.out" 2>&1 || {
    log "FAIL: --delete with missing config_file exited non-zero"
    cat "$WORKDIR/t4.out"
    exit 1
}
assert_present "Config file absent" "$WORKDIR/t4.out" "logged missing config_file"
if [[ -d "$CERT_DIR/c.example.com" ]]; then
    assert_eq "removed" "still present" "c.example.com dir removed even without config"
else
    assert_eq "ok" "ok" "c.example.com dir removed even without config"
fi

# --- Test 5: cert dir present but TOML block absent (operator half-state) ---
# Reproduces the state left behind by a manual `rm -rf $CERT_DIR/<dom>` or
# an interrupted earlier run. The script should remove the orphan directory
# and leave the config file untouched (since there's nothing to splice).
log "Test 5: cert dir present, TOML block absent"
mkdir -p "$CERT_DIR/d.example.com"
echo "fake" > "$CERT_DIR/d.example.com/fullchain.pem"
cat > "$CONFIG_FILE" <<EOF
# Custom Domain Traefik Configuration

[[tls.certificates]]
  certFile = "$CERT_DIR/sibling.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/sibling.example.com/privkey.pem"
EOF
bash "$TARGET_SCRIPT" --delete d.example.com > "$WORKDIR/t5.out" 2>&1 || {
    log "FAIL: cert-dir-only delete exited non-zero"
    cat "$WORKDIR/t5.out"
    exit 1
}
if [[ -d "$CERT_DIR/d.example.com" ]]; then
    assert_eq "removed" "still present" "d.example.com dir removed (no TOML block to splice)"
else
    assert_eq "ok" "ok" "d.example.com dir removed (no TOML block to splice)"
fi
assert_present "sibling.example.com" "$CONFIG_FILE" "sibling TOML block preserved through cert-dir-only delete"

# --- Test 6: TOML block present but cert dir absent (operator half-state) ---
# Reproduces a stale TOML reference after a manual rm -rf $CERT_DIR/<dom>/.
# The script should splice the orphan block out and not complain about the
# missing directory.
log "Test 6: TOML block present, cert dir absent"
rm -rf "$CERT_DIR/e.example.com"
cat > "$CONFIG_FILE" <<EOF
# Custom Domain Traefik Configuration

[[tls.certificates]]
  certFile = "$CERT_DIR/e.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/e.example.com/privkey.pem"

[[tls.certificates]]
  certFile = "$CERT_DIR/sibling.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/sibling.example.com/privkey.pem"
EOF
bash "$TARGET_SCRIPT" --delete e.example.com > "$WORKDIR/t6.out" 2>&1 || {
    log "FAIL: block-only delete exited non-zero"
    cat "$WORKDIR/t6.out"
    exit 1
}
assert_present "already absent" "$WORKDIR/t6.out" "logged 'already absent' for missing cert dir"
assert_absent "e.example.com/fullchain.pem" "$CONFIG_FILE" "orphan e.example.com TOML block spliced out"
assert_present "sibling.example.com" "$CONFIG_FILE" "sibling TOML block preserved through block-only delete"

# --- Summary -----------------------------------------------------------------
log "--------------------------------------------------"
log "Passed: $PASS"
log "Failed: $FAIL"
if (( FAIL > 0 )); then
    exit 1
fi
log "ALL OK"
