#!/usr/bin/env bash
# Local fixture test for custom-domain-cert-sync.sh: --delete mode (#1994) and
# the non-root transition-safety / sentinel fail-loud logic (#1090, Test 7).
#
# Runs in a tmp dir, no AWS calls, no sudo. Designed to be runnable on a dev
# laptop and in CI (lint workflow). Not a smoke test — that's tests/smoke/.
#
# Invocation:
#   bash terraform/modules/ac/scripts/test-cert-sync-delete.sh
#
# The AC script chowns its outputs to $TRAEFIK_USER (default nhp-traefik, which
# is absent on a dev box so it falls back to ubuntu) and calls `aws cloudwatch`.
# Both would explode on a dev box, so we override them via PATH shim.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET_SCRIPT="${SCRIPT_DIR}/custom-domain-cert-sync.sh"

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT

SHIM_DIR="$WORKDIR/shims"
mkdir -p "$SHIM_DIR"

# Override chown to a no-op (would require root for ubuntu:ubuntu locally).
cat > "$SHIM_DIR/chown" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
chmod +x "$SHIM_DIR/chown"

# Track aws invocations to fence "delete mode does not consult SSM" and
# captures the cloudwatch put-metric-data we DO expect.
AWS_CALLS="$WORKDIR/aws-calls.log"
cat > "$SHIM_DIR/aws" <<EOF
#!/usr/bin/env bash
echo "\$@" >> "$AWS_CALLS"
if [[ "\$*" == *"ssm get-parameters-by-path"* && -n "\${AWS_PARAMS_JSON_FILE:-}" ]]; then
  cat "\$AWS_PARAMS_JSON_FILE"
  exit 0
fi
if [[ "\$*" == *"ssm get-parameter"* ]]; then
  if [[ "\$*" == *"/key"* && -n "\${AWS_KEY_VALUE_FILE:-}" ]]; then
    cat "\$AWS_KEY_VALUE_FILE"
    exit 0
  fi
  if [[ "\$*" == *"/chain"* && -n "\${AWS_CHAIN_VALUE_FILE:-}" ]]; then
    cat "\$AWS_CHAIN_VALUE_FILE"
    exit 0
  fi
fi
exit 0
EOF
chmod +x "$SHIM_DIR/aws"

export PATH="$SHIM_DIR:$PATH"
export TRAEFIK_DIR="$WORKDIR/traefik"
export AWS_REGION="us-east-2"

CERT_DIR="$TRAEFIK_DIR/certs/custom-domains"
CONFIG_FILE="$TRAEFIK_DIR/custom-domains.toml"

# --- Fixture: two domains, two TOML blocks ----------------------------------
mkdir -p "$CERT_DIR/a.example.com" "$CERT_DIR/b.example.com"
echo "fake-fullchain-a" > "$CERT_DIR/a.example.com/fullchain.pem"
echo "fake-key-a" > "$CERT_DIR/a.example.com/privkey.pem"
echo "fake-fullchain-b" > "$CERT_DIR/b.example.com/fullchain.pem"
echo "fake-key-b" > "$CERT_DIR/b.example.com/privkey.pem"

mkdir -p "$TRAEFIK_DIR"
cat > "$CONFIG_FILE" <<EOF
# Custom Domain Traefik Configuration
# Auto-generated by custom-domain-cert-sync.sh

[[tls.certificates]]
  certFile = "$CERT_DIR/a.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/a.example.com/privkey.pem"

[[tls.certificates]]
  certFile = "$CERT_DIR/b.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/b.example.com/privkey.pem"
EOF

PASS=0
FAIL=0
log() { echo "[test-cert-sync-delete] $*"; }
assert_eq() {
    local expected="$1" actual="$2" desc="$3"
    if [[ "$expected" == "$actual" ]]; then
        log "PASS: $desc"
        PASS=$((PASS + 1))
    else
        log "FAIL: $desc"
        log "  expected: $expected"
        log "  actual:   $actual"
        FAIL=$((FAIL + 1))
    fi
}
assert_file_eq() {
    local expected_file="$1" actual_file="$2" desc="$3"
    if cmp -s "$expected_file" "$actual_file"; then
        log "PASS: $desc"
        PASS=$((PASS + 1))
    else
        log "FAIL: $desc (files differ)"
        log "  expected_file: $expected_file"
        log "  actual_file:   $actual_file"
        FAIL=$((FAIL + 1))
    fi
}
assert_present() {
    local pattern="$1" file="$2" desc="$3"
    if grep -Fq "$pattern" "$file"; then
        log "PASS: $desc"
        PASS=$((PASS + 1))
    else
        log "FAIL: $desc (pattern not in $file)"
        log "  pattern: $pattern"
        FAIL=$((FAIL + 1))
    fi
}
assert_absent() {
    local pattern="$1" file="$2" desc="$3"
    if grep -Fq "$pattern" "$file" 2>/dev/null; then
        log "FAIL: $desc (pattern still in $file)"
        log "  pattern: $pattern"
        FAIL=$((FAIL + 1))
    else
        log "PASS: $desc"
        PASS=$((PASS + 1))
    fi
}
assert_dir_present() {
    local path="$1" desc="$2"
    if [[ -d "$path" ]]; then
        log "PASS: $desc"
        PASS=$((PASS + 1))
    else
        log "FAIL: $desc (directory missing: $path)"
        FAIL=$((FAIL + 1))
    fi
}
assert_dir_absent() {
    local path="$1" desc="$2"
    if [[ -d "$path" ]]; then
        log "FAIL: $desc (directory still present: $path)"
        FAIL=$((FAIL + 1))
    else
        log "PASS: $desc"
        PASS=$((PASS + 1))
    fi
}

# --- Test 1: delete a.example.com leaves b.example.com intact ---------------
log "Test 1: delete one of two domains"
bash "$TARGET_SCRIPT" --delete a.example.com > "$WORKDIR/t1.out" 2>&1 || {
    log "FAIL: --delete a.example.com exited non-zero"
    cat "$WORKDIR/t1.out"
    exit 1
}
if [[ -d "$CERT_DIR/a.example.com" ]]; then
    assert_eq "removed" "still present" "a.example.com dir removed"
else
    assert_eq "ok" "ok" "a.example.com dir removed"
fi
if [[ -d "$CERT_DIR/b.example.com" ]]; then
    assert_eq "ok" "ok" "b.example.com dir preserved"
else
    assert_eq "preserved" "removed" "b.example.com dir preserved"
fi
assert_absent "a.example.com/fullchain.pem" "$CONFIG_FILE" "TOML block for a.example.com removed"
assert_present "b.example.com/fullchain.pem" "$CONFIG_FILE" "TOML block for b.example.com preserved"

# Verify the metric was published (cloudwatch put-metric-data) and SSM
# was NOT consulted (no get-parameter / get-parameters-by-path).
assert_present "cloudwatch put-metric-data" "$AWS_CALLS" "CloudWatch metric published"
assert_present "CertSyncDomainsRemoved" "$AWS_CALLS" "CertSyncDomainsRemoved metric name emitted"
assert_absent "ssm get-parameter" "$AWS_CALLS" "delete mode did not consult SSM"

# --- Test 2: re-run is idempotent -------------------------------------------
log "Test 2: re-run is idempotent (domain already gone)"
bash "$TARGET_SCRIPT" --delete a.example.com > "$WORKDIR/t2.out" 2>&1 || {
    log "FAIL: --delete on absent domain exited non-zero"
    cat "$WORKDIR/t2.out"
    exit 1
}
assert_present "already absent" "$WORKDIR/t2.out" "logged 'already absent' on re-run"
if [[ -d "$CERT_DIR/b.example.com" ]]; then
    assert_eq "ok" "ok" "b.example.com dir still preserved after re-run"
else
    assert_eq "preserved" "removed" "b.example.com dir still preserved after re-run"
fi
# Re-run should NOT publish CertSyncDomainsRemoved a second time — that
# metric is the offboarding-distinct counter. The dedup branch must
# publish CertSyncDomainAlreadyAbsent so operators can tell SNS retries
# apart from genuine offboards. (cr round 1 on #2005.)
assert_present "CertSyncDomainAlreadyAbsent" "$AWS_CALLS" "re-run published CertSyncDomainAlreadyAbsent (dedup distinct from offboard)"

# --- Test 3: invalid domain refused -----------------------------------------
log "Test 3: invalid domain rejected with non-zero exit"
if bash "$TARGET_SCRIPT" --delete "../../etc/passwd" > "$WORKDIR/t3.out" 2>&1; then
    log "FAIL: traversal domain unexpectedly accepted"
    FAIL=$((FAIL + 1))
else
    log "PASS: traversal domain rejected"
    PASS=$((PASS + 1))
fi
if bash "$TARGET_SCRIPT" --delete "*.example.com" > "$WORKDIR/t3b.out" 2>&1; then
    log "FAIL: wildcard domain unexpectedly accepted"
    FAIL=$((FAIL + 1))
else
    log "PASS: wildcard domain rejected"
    PASS=$((PASS + 1))
fi

# --- Test 4: missing config_file does not error -----------------------------
log "Test 4: missing config_file is tolerated"
rm -f "$CONFIG_FILE"
mkdir -p "$CERT_DIR/c.example.com"
bash "$TARGET_SCRIPT" --delete c.example.com > "$WORKDIR/t4.out" 2>&1 || {
    log "FAIL: --delete with missing config_file exited non-zero"
    cat "$WORKDIR/t4.out"
    exit 1
}
assert_present "Config file absent" "$WORKDIR/t4.out" "logged missing config_file"
if [[ -d "$CERT_DIR/c.example.com" ]]; then
    assert_eq "removed" "still present" "c.example.com dir removed even without config"
else
    assert_eq "ok" "ok" "c.example.com dir removed even without config"
fi

# --- Test 5: cert dir present but TOML block absent (operator half-state) ---
# Reproduces the state left behind by a manual `rm -rf $CERT_DIR/<dom>` or
# an interrupted earlier run. The script should remove the orphan directory
# and leave the config file untouched (since there's nothing to splice).
log "Test 5: cert dir present, TOML block absent"
mkdir -p "$CERT_DIR/d.example.com"
echo "fake" > "$CERT_DIR/d.example.com/fullchain.pem"
cat > "$CONFIG_FILE" <<EOF
# Custom Domain Traefik Configuration

[[tls.certificates]]
  certFile = "$CERT_DIR/sibling.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/sibling.example.com/privkey.pem"
EOF
bash "$TARGET_SCRIPT" --delete d.example.com > "$WORKDIR/t5.out" 2>&1 || {
    log "FAIL: cert-dir-only delete exited non-zero"
    cat "$WORKDIR/t5.out"
    exit 1
}
if [[ -d "$CERT_DIR/d.example.com" ]]; then
    assert_eq "removed" "still present" "d.example.com dir removed (no TOML block to splice)"
else
    assert_eq "ok" "ok" "d.example.com dir removed (no TOML block to splice)"
fi
assert_present "sibling.example.com" "$CONFIG_FILE" "sibling TOML block preserved through cert-dir-only delete"

# --- Test 6: TOML block present but cert dir absent (operator half-state) ---
# Reproduces a stale TOML reference after a manual rm -rf $CERT_DIR/<dom>/.
# The script should splice the orphan block out and not complain about the
# missing directory.
log "Test 6: TOML block present, cert dir absent"
rm -rf "$CERT_DIR/e.example.com"
cat > "$CONFIG_FILE" <<EOF
# Custom Domain Traefik Configuration

[[tls.certificates]]
  certFile = "$CERT_DIR/e.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/e.example.com/privkey.pem"

[[tls.certificates]]
  certFile = "$CERT_DIR/sibling.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/sibling.example.com/privkey.pem"
EOF
bash "$TARGET_SCRIPT" --delete e.example.com > "$WORKDIR/t6.out" 2>&1 || {
    log "FAIL: block-only delete exited non-zero"
    cat "$WORKDIR/t6.out"
    exit 1
}
assert_present "already absent" "$WORKDIR/t6.out" "logged 'already absent' for missing cert dir"
assert_absent "e.example.com/fullchain.pem" "$CONFIG_FILE" "orphan e.example.com TOML block spliced out"
assert_present "sibling.example.com" "$CONFIG_FILE" "sibling TOML block preserved through block-only delete"

# --- Test 7: non-root user fallback + sentinel fail-loud (#1090) -------------
# The transition-safety logic at the top of the script: when $TRAEFIK_USER is
# absent it either benignly falls back to `ubuntu` (genuine pre-#1090 box, no
# sentinel) or fails LOUD (sentinel present => refreshed box with partial
# user_data; must not silently re-own the 0600 privkey to ubuntu). `id -u` on a
# guaranteed-absent user drives the branch without a shim.
log "Test 7a: sentinel ABSENT + nhp user absent -> benign WARN fallback to ubuntu"
SENTINEL="$WORKDIR/nonroot-sentinel"
rm -f "$SENTINEL"
mkdir -p "$CERT_DIR/f.example.com"
echo "fake" > "$CERT_DIR/f.example.com/fullchain.pem"
if SENTINEL_FILE="$SENTINEL" TRAEFIK_USER="nhp-absent-test-user" \
     bash "$TARGET_SCRIPT" --delete f.example.com > "$WORKDIR/t7a.out" 2>&1; then
    assert_present "WARN: user 'nhp-absent-test-user' absent" "$WORKDIR/t7a.out" "benign fallback logs WARN and continues"
else
    log "FAIL: benign fallback (no sentinel) exited non-zero"
    cat "$WORKDIR/t7a.out"
    FAIL=$((FAIL + 1))
fi

log "Test 7b: sentinel PRESENT + nhp user absent -> FATAL exit 1 (no silent re-own)"
touch "$SENTINEL"
mkdir -p "$CERT_DIR/g.example.com"
if SENTINEL_FILE="$SENTINEL" TRAEFIK_USER="nhp-absent-test-user" \
     bash "$TARGET_SCRIPT" --delete g.example.com > "$WORKDIR/t7b.out" 2>&1; then
    log "FAIL: sentinel-present + absent user did NOT fail loud"
    cat "$WORKDIR/t7b.out"
    FAIL=$((FAIL + 1))
else
    assert_present "FATAL" "$WORKDIR/t7b.out" "sentinel-present + absent user fails loud (FATAL, exit 1)"
fi

# --- Test 8: incremental mismatch must not overwrite existing live files -----
log "Test 8: incremental key/cert mismatch preserves existing live cert files"
mkdir -p "$CERT_DIR/mismatch.example.com"
printf "old-fullchain\n" > "$CERT_DIR/mismatch.example.com/fullchain.pem"
printf "old-key\n" > "$CERT_DIR/mismatch.example.com/privkey.pem"
cat > "$CONFIG_FILE" <<EOF
# Custom Domain Traefik Configuration

[[tls.certificates]]
  certFile = "$CERT_DIR/mismatch.example.com/fullchain.pem"
  keyFile = "$CERT_DIR/mismatch.example.com/privkey.pem"
EOF
openssl genrsa -out "$WORKDIR/mismatch-good.key" 2048 >/dev/null 2>&1
openssl req -new -x509 -key "$WORKDIR/mismatch-good.key" \
  -out "$WORKDIR/mismatch.crt" -subj "/CN=mismatch.example.com" -days 1 >/dev/null 2>&1
openssl genrsa -out "$WORKDIR/mismatch-bad.key" 2048 >/dev/null 2>&1
if AWS_KEY_VALUE_FILE="$WORKDIR/mismatch-bad.key" AWS_CHAIN_VALUE_FILE="$WORKDIR/mismatch.crt" \
     bash "$TARGET_SCRIPT" --domain mismatch.example.com > "$WORKDIR/t8.out" 2>&1; then
    log "FAIL: mismatched incremental sync unexpectedly succeeded"
    cat "$WORKDIR/t8.out"
    FAIL=$((FAIL + 1))
else
    assert_present "Certificate/key mismatch" "$WORKDIR/t8.out" "mismatched SSM material is rejected"
fi
assert_eq "old-fullchain" "$(tr -d '\n' < "$CERT_DIR/mismatch.example.com/fullchain.pem")" "existing fullchain preserved after mismatch"
assert_eq "old-key" "$(tr -d '\n' < "$CERT_DIR/mismatch.example.com/privkey.pem")" "existing private key preserved after mismatch"
assert_present "mismatch.example.com/fullchain.pem" "$CONFIG_FILE" "existing TOML block preserved after mismatch"

# --- Test 9: stale temp cert dirs are swept on startup -------------------------
log "Test 9: stale temp cert dirs are swept on startup"
STALE_TMP_DIR="$CERT_DIR/.stale.example.com.tmp.ABC123"
STALE_OLD_DIR="$CERT_DIR/.stale.example.com.old.ABC123"
FRESH_TMP_DIR="$CERT_DIR/.fresh.example.com.tmp.ABC123"
mkdir -p "$STALE_TMP_DIR" "$STALE_OLD_DIR" "$FRESH_TMP_DIR"
printf "stale-key\n" > "$STALE_TMP_DIR/privkey.pem"
printf "stale-key\n" > "$STALE_OLD_DIR/privkey.pem"
printf "fresh-key\n" > "$FRESH_TMP_DIR/privkey.pem"
touch -t 202001010000 "$STALE_TMP_DIR" "$STALE_OLD_DIR"
bash "$TARGET_SCRIPT" --delete cleanup-missing.example.com > "$WORKDIR/t9.out" 2>&1 || {
    log "FAIL: --delete cleanup-missing.example.com exited non-zero"
    cat "$WORKDIR/t9.out"
    exit 1
}
assert_dir_absent "$STALE_TMP_DIR" "stale staging dir removed on startup"
assert_dir_absent "$STALE_OLD_DIR" "stale backup dir removed on startup"
assert_dir_present "$FRESH_TMP_DIR" "fresh staging dir preserved on startup"

# --- Test 10: ECDSA cert/key pairs are accepted -------------------------------
log "Test 10: ECDSA incremental sync is accepted"
openssl ecparam -name prime256v1 -genkey -noout -out "$WORKDIR/ecdsa.key" >/dev/null 2>&1
openssl req -new -x509 -key "$WORKDIR/ecdsa.key" \
  -out "$WORKDIR/ecdsa.crt" -subj "/CN=ecdsa.example.com" -days 1 >/dev/null 2>&1
if AWS_KEY_VALUE_FILE="$WORKDIR/ecdsa.key" AWS_CHAIN_VALUE_FILE="$WORKDIR/ecdsa.crt" \
     bash "$TARGET_SCRIPT" --domain ecdsa.example.com > "$WORKDIR/t10.out" 2>&1; then
    assert_present "Certificate loaded" "$WORKDIR/t10.out" "ECDSA cert/key pair loads"
else
    log "FAIL: ECDSA incremental sync exited non-zero"
    cat "$WORKDIR/t10.out"
    FAIL=$((FAIL + 1))
fi
assert_dir_present "$CERT_DIR/ecdsa.example.com" "ECDSA cert directory installed"
assert_present "ecdsa.example.com/fullchain.pem" "$CONFIG_FILE" "ECDSA TOML block written"

# --- Test 11: full sync preserves present-but-invalid SSM domains -------------
log "Test 11: full sync mismatch preserves last-known-good live cert"
FULL_MISMATCH_DOMAIN="full-mismatch.example.com"
FULL_EXPIRED_DOMAIN="full-expired.example.com"
FULL_STALE_DOMAIN="full-stale.example.com"
FULL_ACTIVE_SUBDOMAIN="a.example.com"
FULL_OVERLAP_STALE_DOMAIN="example.com"
mkdir -p \
  "$CERT_DIR/$FULL_MISMATCH_DOMAIN" \
  "$CERT_DIR/$FULL_EXPIRED_DOMAIN" \
  "$CERT_DIR/$FULL_STALE_DOMAIN" \
  "$CERT_DIR/$FULL_OVERLAP_STALE_DOMAIN"
printf "stale-fullchain\n" > "$CERT_DIR/$FULL_STALE_DOMAIN/fullchain.pem"
printf "stale-key\n" > "$CERT_DIR/$FULL_STALE_DOMAIN/privkey.pem"
printf "overlap-stale-fullchain\n" > "$CERT_DIR/$FULL_OVERLAP_STALE_DOMAIN/fullchain.pem"
printf "overlap-stale-key\n" > "$CERT_DIR/$FULL_OVERLAP_STALE_DOMAIN/privkey.pem"
cat > "$CONFIG_FILE" <<EOF
# Custom Domain Traefik Configuration

[[tls.certificates]]
  certFile = "$CERT_DIR/$FULL_MISMATCH_DOMAIN/fullchain.pem"
  keyFile = "$CERT_DIR/$FULL_MISMATCH_DOMAIN/privkey.pem"

[[tls.certificates]]
  certFile = "$CERT_DIR/$FULL_EXPIRED_DOMAIN/fullchain.pem"
  keyFile = "$CERT_DIR/$FULL_EXPIRED_DOMAIN/privkey.pem"

[[tls.certificates]]
  certFile = "$CERT_DIR/$FULL_STALE_DOMAIN/fullchain.pem"
  keyFile = "$CERT_DIR/$FULL_STALE_DOMAIN/privkey.pem"

[[tls.certificates]]
  certFile = "$CERT_DIR/$FULL_OVERLAP_STALE_DOMAIN/fullchain.pem"
  keyFile = "$CERT_DIR/$FULL_OVERLAP_STALE_DOMAIN/privkey.pem"
EOF
openssl genrsa -out "$WORKDIR/full-good.key" 2048 >/dev/null 2>&1
openssl req -new -x509 -key "$WORKDIR/full-good.key" \
  -out "$WORKDIR/full.crt" -subj "/CN=$FULL_MISMATCH_DOMAIN" -days 1 >/dev/null 2>&1
openssl genrsa -out "$WORKDIR/full-bad.key" 2048 >/dev/null 2>&1
cp "$WORKDIR/full.crt" "$CERT_DIR/$FULL_MISMATCH_DOMAIN/fullchain.pem"
cp "$WORKDIR/full-good.key" "$CERT_DIR/$FULL_MISMATCH_DOMAIN/privkey.pem"
openssl genrsa -out "$WORKDIR/full-expired.key" 2048 >/dev/null 2>&1
openssl x509 -new -key "$WORKDIR/full-expired.key" \
  -out "$WORKDIR/full-expired.crt" -subj "/CN=$FULL_EXPIRED_DOMAIN" \
  -not_before 20240101000000Z -not_after 20240102000000Z >/dev/null 2>&1
if openssl x509 -in "$WORKDIR/full-expired.crt" -noout -enddate >/dev/null 2>&1 && \
   ! openssl x509 -in "$WORKDIR/full-expired.crt" -noout -checkend 0 >/dev/null 2>&1; then
    log "PASS: expired fixture is parseable and past notAfter"
    PASS=$((PASS + 1))
else
    log "FAIL: expired fixture is not a parseable expired certificate"
    FAIL=$((FAIL + 1))
fi
cp "$WORKDIR/full-expired.crt" "$CERT_DIR/$FULL_EXPIRED_DOMAIN/fullchain.pem"
cp "$WORKDIR/full-expired.key" "$CERT_DIR/$FULL_EXPIRED_DOMAIN/privkey.pem"
openssl genrsa -out "$WORKDIR/full-active.key" 2048 >/dev/null 2>&1
openssl req -new -x509 -key "$WORKDIR/full-active.key" \
  -out "$WORKDIR/full-active.crt" -subj "/CN=$FULL_ACTIVE_SUBDOMAIN" -days 1 >/dev/null 2>&1
FULL_KEY_JSON=$(jq -Rs . < "$WORKDIR/full-bad.key")
FULL_CHAIN_JSON=$(jq -Rs . < "$WORKDIR/full.crt")
FULL_EXPIRED_KEY_JSON=$(jq -Rs . < "$WORKDIR/full-expired.key")
FULL_EXPIRED_CHAIN_JSON=$(jq -Rs . < "$WORKDIR/full-expired.crt")
FULL_ACTIVE_KEY_JSON=$(jq -Rs . < "$WORKDIR/full-active.key")
FULL_ACTIVE_CHAIN_JSON=$(jq -Rs . < "$WORKDIR/full-active.crt")
cat > "$WORKDIR/full-params.json" <<EOF
{"Parameters":[
  {"Name":"/nhp/certs/$FULL_MISMATCH_DOMAIN/key","Value":$FULL_KEY_JSON},
  {"Name":"/nhp/certs/$FULL_MISMATCH_DOMAIN/chain","Value":$FULL_CHAIN_JSON},
  {"Name":"/nhp/certs/$FULL_EXPIRED_DOMAIN/key","Value":$FULL_EXPIRED_KEY_JSON},
  {"Name":"/nhp/certs/$FULL_EXPIRED_DOMAIN/chain","Value":$FULL_EXPIRED_CHAIN_JSON},
  {"Name":"/nhp/certs/$FULL_ACTIVE_SUBDOMAIN/key","Value":$FULL_ACTIVE_KEY_JSON},
  {"Name":"/nhp/certs/$FULL_ACTIVE_SUBDOMAIN/chain","Value":$FULL_ACTIVE_CHAIN_JSON}
]}
EOF
AWS_PARAMS_JSON_FILE="$WORKDIR/full-params.json" bash "$TARGET_SCRIPT" > "$WORKDIR/t11.out" 2>&1 || {
    log "FAIL: full sync mismatch fixture exited non-zero"
    cat "$WORKDIR/t11.out"
    exit 1
}
assert_present "Preserving existing certificate for $FULL_MISMATCH_DOMAIN" "$WORKDIR/t11.out" "full sync preserves present mismatched domain"
assert_present "Existing certificate for $FULL_EXPIRED_DOMAIN is expired or invalid; not preserving" "$WORKDIR/t11.out" "full sync refuses to preserve expired local cert"
assert_file_eq "$WORKDIR/full.crt" "$CERT_DIR/$FULL_MISMATCH_DOMAIN/fullchain.pem" "full sync keeps old fullchain after mismatch"
assert_file_eq "$WORKDIR/full-good.key" "$CERT_DIR/$FULL_MISMATCH_DOMAIN/privkey.pem" "full sync keeps old private key after mismatch"
assert_dir_absent "$CERT_DIR/$FULL_EXPIRED_DOMAIN" "full sync removes expired local cert instead of preserving"
assert_dir_absent "$CERT_DIR/$FULL_STALE_DOMAIN" "full sync still removes domains absent from SSM"
assert_dir_absent "$CERT_DIR/$FULL_OVERLAP_STALE_DOMAIN" "full sync exact-match cleanup removes parent domain when only subdomain is active"
assert_dir_present "$CERT_DIR/$FULL_ACTIVE_SUBDOMAIN" "full sync installs active subdomain fixture"
assert_present "$FULL_MISMATCH_DOMAIN/fullchain.pem" "$CONFIG_FILE" "full sync keeps TOML block for mismatched present domain"
assert_absent "$FULL_EXPIRED_DOMAIN/fullchain.pem" "$CONFIG_FILE" "full sync removes TOML block for expired local cert"
assert_absent "$FULL_STALE_DOMAIN/fullchain.pem" "$CONFIG_FILE" "full sync removes TOML block for absent stale domain"
assert_absent "$CERT_DIR/$FULL_OVERLAP_STALE_DOMAIN/fullchain.pem" "$CONFIG_FILE" "full sync removes TOML block for exact-match stale parent domain"

# --- Summary -----------------------------------------------------------------
log "--------------------------------------------------"
log "Passed: $PASS"
log "Failed: $FAIL"
if (( FAIL > 0 )); then
    exit 1
fi
log "ALL OK"
